if(typeof dartCallbackObjects=="undefined")var dartCallbackObjects=new Array;if(typeof dartCreativeDisplayManagers=="undefined")var dartCreativeDisplayManagers=new Object;if(typeof dartMotifAds=="undefined")var dartMotifAds=new Array;if(!self.dartLoadedGlobalTemplates_60_15)self.dartLoadedGlobalTemplates_60_15={};if(self.dartLoadedGlobalTemplates_60_15["expanding"])self.dartLoadedGlobalTemplates_60_15["expanding"].isLoaded=true;
function RichMediaCreativeDisplayManager_60_15(a,b){this.creative=a;this.creativeIdentifier=a.creativeIdentifier;this.previewMode=a.previewMode;this.debugEventsMode=a.debugEventsMode;this.renderingId=a.renderingId;this.creativeType=a.type;this.mtfNoFlush=a.mtfNoFlush;this.dartPopupArray=new Object;this.isDisplayTimerRunning=false;this.fsCommandHandlers=new Object;this.rootElementArray=new Array;this.sourceIframe=typeof b!="undefined"?b:null;this.overlay=null;this.dartEventBin=null;this.previewHandler=
null;this.importantEventArray=new Array(this.STANDARD_EVENT_INTERACTIVE_IMPRESSION,this.STANDARD_EVENT_VIDEO_PLAY,this.STANDARD_EVENT_VIDEO_VIEW_COMPLETE,this.STANDARD_EVENT_EXPAND_TIMER,this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION);this.adListener=null;this.init(a);dartMotifAds[dartMotifAds.length]=this.creative}/*RichMediaCreativeDisplayManager_60_15.prototype=new RichMediaCore_60_15;*/
RichMediaCreativeDisplayManager_60_15.prototype.init=function(a){this.buildImportantEventList(a);this.createEventBin(a);this.assets=new Object;if(this.creative.assets["floatAssets"])for(var b=0;b<this.creative.assets["floatAssets"].length;b++){var c=this.creative.assets["floatAssets"][b];this.assets[c.variableName]=c}else for(var d in this.creative.assets)if(!this.isPartOfArrayPrototype(d)){c=this.creative.assets[d];this.assets[c.variableName]=c}if(a.type==this.CREATIVE_TYPE_FLOATING_WITH_REMINDER||
a.type==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING||a.type==this.CREATIVE_TYPE_MULTI_FLOATING||a.type==this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY)this.dualAssetManager=new DualAssetManager_60_15(a,this);if(a.type==this.CREATIVE_TYPE_EXPANDING||a.type==this.CREATIVE_TYPE_FLOATING||a.type==this.CREATIVE_TYPE_FLOATING_WITH_REMINDER||a.type==this.CREATIVE_TYPE_MULTI_FLOATING||a.type==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING)this.pageElementsManager=new PageElementsManager_60_15(a,this)};
RichMediaCreativeDisplayManager_60_15.prototype.buildImportantEventList=function(a){for(var b=0;b<this.importantEventArray.length;b++)this.importantEventArray[b]=this.getStandardEventId(this.importantEventArray[b]);for(var c in a.videoComponents)if(!this.isPartOfArrayPrototype(c)){this.importantEventArray[this.importantEventArray.length]=this.getCustomVideoEventId("Count",c,this.STANDARD_EVENT_VIDEO_PLAY);this.importantEventArray[this.importantEventArray.length]=this.getCustomVideoEventId("Count",
c,this.STANDARD_EVENT_VIDEO_VIEW_COMPLETE)}for(var d in a.exitEvents)if(!this.isPartOfArrayPrototype(d))this.importantEventArray[this.importantEventArray.length]=this.getEventId("Exit",d)};
RichMediaCreativeDisplayManager_60_15.prototype.createEventBin=function(a){if(!this.previewMode)this.dartEventBin=new RichMediaEventBin_60_15(this.creativeIdentifier,this.mtfNoFlush,this.importantEventArray);else if(this.debugEventsMode){this.initDebugHandler(a);var b=this.getSourceIframe();if(typeof DebugEventBin_60_15!="undefined")this.dartDebugEventBin=new DebugEventBin_60_15(this.creativeIdentifier,this.previewHandler);else if(this.isServedInIframe()&&typeof b.contentWindow.DebugEventBin_60_15!=
"undefined")this.dartDebugEventBin=new b.contentWindow.DebugEventBin_60_15(this.creativeIdentifier,this.previewHandler)}};RichMediaCreativeDisplayManager_60_15.prototype.initDebugHandler=function(a){try{if(typeof DARTDebugEventHandler!="undefined")this.previewHandler=new DARTDebugEventHandler;else if(typeof self.parent.DARTDebugEventHandler!="undefined"){self.parent.globalTemplatePreviewHandler=new self.parent.DARTDebugEventHandler;this.previewHandler=self.parent.globalTemplatePreviewHandler}}catch(b){}};
RichMediaCreativeDisplayManager_60_15.prototype.deleteCreative=function(a){this.deleteJSObjects();if(!a)this.deleteHTMLObjects()};RichMediaCreativeDisplayManager_60_15.prototype.deleteHTMLObjects=function(){for(var a=0;a<this.rootElementArray.length;a++)if(this.rootElementArray[a]!=null&&this.rootElementArray[a].parentNode!=null)this.removeChildNode(this.rootElementArray[a],this.rootElementArray[a].parentNode)};
RichMediaCreativeDisplayManager_60_15.prototype.deleteJSObjects=function(){if(this.creative.isInterstitial)DoNotDisplayIA=null;this.detachFSCommandHandler();this.setShouldFlush(this.renderingId,false);this.removeArrayElement(dartCallbackObjects,this.dartEventBin);this.dartEventBin=null};RichMediaCreativeDisplayManager_60_15.prototype.removeArrayElement=function(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)a[c]=null};
RichMediaCreativeDisplayManager_60_15.prototype.fsHook=function(a){var b="";b+=a+"_DoFSCommand = function(command, args) { \n";b+='    if(dartCreativeDisplayManagers["'+this.creativeIdentifier+'"] != null) dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].FSCommandHandler(command, args);\n';b+="}\n";window.eval(b);if(this.isInternetExplorer()){var c=this.toObject(a);var d=eval(a+"_DoFSCommand");this.fsCommandHandlers[a]=d;if(c.attachEvent("FSCommand",d))this.registerPageUnLoadHandler("detachFSCommandHandler()",
this)}};RichMediaCreativeDisplayManager_60_15.prototype.registerFSCommandHandler=function(a){if(this.isInternetExplorer()){var b=this.toObject("FLASH_"+a);var c=this.fsCommandHandlers["FLASH_"+a];if(b.attachEvent("FSCommand",c))this.registerPageUnLoadHandler("detachFSCommandHandler()",this)}};
RichMediaCreativeDisplayManager_60_15.prototype.detachFSCommandHandler=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a)){var b="FLASH_"+a;var c=this.toObject(b);var d=this.fsCommandHandlers[b];if(c!=null)if(this.isInternetExplorer())c.detachEvent("FSCommand",d)}};
RichMediaCreativeDisplayManager_60_15.prototype.FSCommandHandler=function(a,b){if(a=="mtfCommands"){var c=b.split("&");for(var d=0;d<c.length;d++){var e=this._parseCommandString(c[d]);var f=this.createFunctionCall(e.command,e.argArray);try{eval('dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+f)}catch(g){f=e.command+"('"+e.argString+"')";try{eval(f)}catch(h){}}}}else{var i=this._splitArgs(b);f=this.createFunctionCall(a,i);try{return eval('dartCreativeDisplayManagers["'+this.creativeIdentifier+
'"].'+f)}catch(j){try{eval(f)}catch(k){}}}};RichMediaCreativeDisplayManager_60_15.prototype.setFocus=function(a){var b=this.toObject("FLASH_"+a);if(b!=null)if(this.isFirefox()&&this.isMac()){var c=this.getFireFoxVersion();if(c>=2&&c<3){b.blur();window.blur()}}};
RichMediaCreativeDisplayManager_60_15.prototype.reportCustomVariable=function(a,b){if(!this.previewMode){var c=this.creative.stringPostingUrl;var d=new Date;c+="&timestamp="+d.getTime()+";"+"str="+unescape(a)+";"+"strtype="+b;var e=document.createElement("img");e.src=c}else{var f=this.getEventBin();if(f!=null)f.logCustomVariable(unescape(a),b,this.creative.renderingId)}};
RichMediaCreativeDisplayManager_60_15.prototype.setDynamicServeId=function(a){var b=this.getEventBin();if(b){b.setDynamicServeId(a);var c=this.getStandardEventId(this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION);b.logMetEvent("Count",c,this.creative.renderingId,false,this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION);b.flushMetCounters(this.creative.renderingId)}};
RichMediaCreativeDisplayManager_60_15.prototype.getFireFoxVersion=function(){var a=navigator.userAgent.toUpperCase();if(a.indexOf("GECKO")!=-1)if(a.indexOf("FIREFOX")!=-1)return parseFloat(a.substr(a.lastIndexOf("/")+1));return null};
RichMediaCreativeDisplayManager_60_15.prototype.conduitInitialized=function(a){if(this.creative.shouldDisplayHTML5Asset)this.setAdParameters();else{/*RichMediaCore_60_15.prototype.trackCsiEvent("fe");*/var b=this.getAsset(a);b.conduitInitialized=true;if(this.shouldCsi(b,this.creative.type))/*RichMediaCore_60_15.prototype.reportCsi(this.creative)}};*/RichMediaCreativeDisplayManager_60_15.prototype.setTimerAdjustment=function(a,b,c){this.getEventBin().setTimerAdjustment(a,b,c)};
RichMediaCreativeDisplayManager_60_15.prototype.getEventBin=function(){if(!this.previewMode)return this.dartEventBin;else if(this.debugEventsMode)return this.dartDebugEventBin;else return null};RichMediaCreativeDisplayManager_60_15.prototype.getStandardEventId=function(a){return this.creative.standardEvents[a].reportingId};
RichMediaCreativeDisplayManager_60_15.prototype.getEventId=function(a,b){var c;if(a=="Start"||a=="Stop")c=this.creative.timerEvents[b];else if(a=="Count")c=this.creative.counterEvents[b];else if(a=="Exit")c=this.creative.exitEvents[b];return c!=null?c.reportingId:-1};RichMediaCreativeDisplayManager_60_15.prototype.evaluateBoolean=function(a){var b=typeof a;return b=="string"&&a=="true"||b=="boolean"&&a};
RichMediaCreativeDisplayManager_60_15.prototype.logEvent=function(a,b,c,d,e){var f;b=unescape(b);e=this.evaluateBoolean(e);d=this.evaluateBoolean(d);if(e)f=this.getEventId(a,b);else f=this.getStandardEventId(b);if(f==-1)return;if(a==="Exit")a="Count";if(b==this.STANDARD_EVENT_DISPLAY_TIMER)this.logDisplayTimerEvent(a,c);else{var g=this.getEventBin();if(g)g.logMetEvent(a,f,c,d,b)}};
RichMediaCreativeDisplayManager_60_15.prototype.getCustomVideoEventId=function(a,b,c){var d=this.getStandardEventId(c);var e;if(a=="Start"||a=="Stop")e=this.creative.timerEvents;else e=this.creative.counterEvents;var f="";for(var g in e){var h=e[g];if(h.sourceComponentName==b&&h.sourceStandardEventId==d){f=h.reportingId;break}}return f};
RichMediaCreativeDisplayManager_60_15.prototype.logVideoEvent=function(a,b,c){b=unescape(b);var d=this.creative.videoComponents[b];var e=this.getEventBin();var f=this.getStandardEventId(c);if(e)e.logMetEvent(a,f,this.creative.renderingId,false,c);if(d.trackCustomEvents){var g=this.getCustomVideoEventId(a,b,c);if(e)e.logMetEvent(a,g,this.creative.renderingId,false,c)}};
RichMediaCreativeDisplayManager_60_15.prototype.stopStandardTimers=function(a){this.logEvent("Stop",this.STANDARD_EVENT_DISPLAY_TIMER,a);this.logEvent("Stop",this.STANDARD_EVENT_INTERACTION_TIMER,a);this.logEvent("Stop",this.STANDARD_EVENT_VIDEO_VIEW_TIMER,a)};
RichMediaCreativeDisplayManager_60_15.prototype.logDisplayTimerEvent=function(a,b){var c=this.getEventBin();if(a=="Start"){if(!this.isDisplayTimerRunning){if(c)c.logMetEvent("Start","2",b);this.isDisplayTimerRunning=true}}else if(a=="Stop")if(this.isDisplayTimerRunning){if(c)c.logMetEvent("Stop","2",b);this.isDisplayTimerRunning=false}};RichMediaCreativeDisplayManager_60_15.prototype.flushCounters=function(a){var b=this.getEventBin();if(b)b.flushMetCounters(a)};
RichMediaCreativeDisplayManager_60_15.prototype.scheduleTurnOffEventBinFlushing=function(a,b){var c=this.getEventBin();if(c)this.registerTimeoutHandler(b*1000,"turnOffFlushing('"+a+"')",c)};RichMediaCreativeDisplayManager_60_15.prototype.setShouldFlush=function(a,b){var c=this.getEventBin();if(c)c.setMetShouldFlush(a,b)};RichMediaCreativeDisplayManager_60_15.prototype.getShouldFlush=function(a){var b=this.getEventBin();return b&&b.getShouldFlush(a)};
RichMediaCreativeDisplayManager_60_15.prototype.registerUrl=function(a,b){var c=this.getEventBin();if(c)c.registerEventBinUrl(a,b)};RichMediaCreativeDisplayManager_60_15.prototype.logExitEventFlushCounters=function(a,b,c,d){this.logEvent("Exit",a,b,c,d);this.flushCounters(b)};RichMediaCreativeDisplayManager_60_15.prototype.logEventFlushCounters=function(a,b,c,d,e){this.logExitEventFlushCounters(b,c,d,e)};
RichMediaCreativeDisplayManager_60_15.prototype._logEventFlushCountersOpenPopup=function(a,b,c,d,e,f,g){this.logEvent(a,b,c,true);this.flushCounters(c);this.openPopup(d,e,f,g)};RichMediaCreativeDisplayManager_60_15.prototype.getExitUrl=function(a,b){var c=b==undefined?this.creative.exitEvents[a].url:b;var d=this.creative.clickThroughUrl;var e=this.creative.clickN!=""?parseInt(this.creative.clickN):1;if(d.indexOf("?")>=0||d.indexOf("&")>=0)for(var f=0;f<e;f++)c=escape(c);return d+c};
RichMediaCreativeDisplayManager_60_15.prototype.logInteractiveImpression=function(){if(!this.interactiveImpressionLogged){this.logEvent("Count",this.STANDARD_EVENT_INTERACTIVE_IMPRESSION);this.interactiveImpressionLogged=true}};
RichMediaCreativeDisplayManager_60_15.prototype.logExitFlushEventsOpenPopup=function(a,b,c,d,e,f){var g=this.creative.exitEvents[b];var h=this.getExitUrl(b);e=e=="null"?null:e;f=(f="null")?null:f;if(e)h=this.getExitUrl(b,f);else if(f!=null&&f!=""){h=h.indexOf("?")!=-1&&f.charAt(0)!="&"&&h.charAt(h.length-1)!="?"?h+"&":h;h=h.indexOf("?")==-1&&f.indexOf("?")==-1?h+"?":h;h+=f}this.logInteractiveImpression();this.logExitEventFlushCounters(b,c,true,true);if(g.customizedWindow)this.openPopup(h,"motifWindow",
g.windowFeatures,false);else this.openPopup(h,"motifWindow",null,false)};RichMediaCreativeDisplayManager_60_15.prototype.setExpandingManager=function(a){this.expandingManager=a};RichMediaCreativeDisplayManager_60_15.prototype.hasExpandingManager=function(){return typeof this.expandingManager!="undefined"};RichMediaCreativeDisplayManager_60_15.prototype.setFloatingManager=function(a){this.floatingManager=a};
RichMediaCreativeDisplayManager_60_15.prototype.hasFloatingManager=function(){return typeof this.floatingManager!="undefined"};RichMediaCreativeDisplayManager_60_15.prototype.expandAsset=function(a){if(this.creative.shouldDisplayHTML5Asset)this.expandHTMLAsset(a);else this.expandFlashAsset(a)};
RichMediaCreativeDisplayManager_60_15.prototype.expandHTMLAsset=function(a){var b=this.getAsset(a);var c=b.expandedWidth!=undefined?b.expandedWidth:b.width;var d=b.expandedHeight!=undefined?b.expandedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;if(e)this._adjustWindowElements(a,true);if(e&&b.pushContents)this.expandingManager.startAnimation(b,true,true);else this.unclipFlashObject(b,c,d,true)};
RichMediaCreativeDisplayManager_60_15.prototype.expandFlashAsset=function(a){var b=this.getAsset(a);var c=b.expandedWidth!=undefined?b.expandedWidth:b.width;var d=b.expandedHeight!=undefined?b.expandedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;var f=this.toObject("FLASH_"+a);var g=this.hasExpandingManager()&&this.expandingManager.isMultiDirectionalExpanding(f);if(e&&!this.isInAdSenseIFrame()&&g)var h=this.expandingManager.getExpandingDirection(b);if(this.adListener)this.adListener.expand();
if(e)this._adjustWindowElements(a,true);if(e&&b.pushContents)this.expandingManager.startAnimation(b,true,false);else this.unclipFlashObject(b,c,d,false);if(e&&g)if(this.isInAdSenseIFrame())this.expandingManager.creativeToolset.expandWindow();else this.multiDirectionExpand(f,h)};RichMediaCreativeDisplayManager_60_15.prototype.multiDirectionExpand=function(a,b){try{this.setFlashVariable(this.creative.asVersion,a,"mde_expandedDirection",b)}catch(c){}};
RichMediaCreativeDisplayManager_60_15.prototype.collapseAsset=function(a){if(this.creative.shouldDisplayHTML5Asset)this.collapseHTMLAsset(a);else this.collapseFlashAsset(a)};
RichMediaCreativeDisplayManager_60_15.prototype.collapseHTMLAsset=function(a){var b=this.getAsset(a);var c=b.collapsedWidth!=undefined?b.collapsedWidth:b.width;var d=b.collapsedHeight!=undefined?b.collapsedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;if(e&&b.pushContents)this.expandingManager.startAnimation(b,false,true);else this.clipFlashObject(b,c,d,b.offsetTop,b.offsetRight,b.offsetBottom,b.offsetLeft,true);if(e)this._adjustWindowElements(a,false)};
RichMediaCreativeDisplayManager_60_15.prototype.collapseFlashAsset=function(a){var b=this.getAsset(a);var c=b.collapsedWidth!=undefined?b.collapsedWidth:b.width;var d=b.collapsedHeight!=undefined?b.collapsedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;if(e&&b.pushContents)this.expandingManager.startAnimation(b,false,false);else this.clipFlashObject(b,c,d,b.offsetTop,b.offsetRight,b.offsetBottom,b.offsetLeft,false);if(e)this._adjustWindowElements(a,false);var f=this.toObject("FLASH_"+
a);var g=this.hasExpandingManager()&&this.expandingManager.isMultiDirectionalExpanding(f);if(e&&g)if(this.isInAdSenseIFrame())this.expandingManager.creativeToolset.collapseWindow();else this.multiDirectionCollapse(f);if(this.adListener)this.adListener.collapse()};RichMediaCreativeDisplayManager_60_15.prototype.multiDirectionCollapse=function(a){try{this.setFlashVariable(this.creative.asVersion,a,"mde_expandedState","collapsed")}catch(b){}};
RichMediaCreativeDisplayManager_60_15.prototype.onMouseOver=function(a){try{var b=this.toObject("FLASH_"+a);this.setFlashVariable(this.creative.asVersion,b,"isMouseOver","1")}catch(c){}};RichMediaCreativeDisplayManager_60_15.prototype.onMouseOut=function(a){try{var b=this.toObject("FLASH_"+a);this.setFlashVariable(this.creative.asVersion,b,"isMouseOver","0")}catch(c){}};
RichMediaCreativeDisplayManager_60_15.prototype.onMouseOverHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","1"],a)}catch(b){}};RichMediaCreativeDisplayManager_60_15.prototype.onMouseOutHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","0"],a)}catch(b){}};RichMediaCreativeDisplayManager_60_15.prototype.onTouchHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","1"],a)}catch(b){}};
RichMediaCreativeDisplayManager_60_15.prototype.onTouchEndHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","0"],a)}catch(b){}};RichMediaCreativeDisplayManager_60_15.prototype.scheduleCallbackOnLoad=function(a){a='dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+a;this.registerPageLoadHandler(a,null)};
RichMediaCreativeDisplayManager_60_15.prototype.scheduleDisplay=function(a,b,c){b=this._convertDuration(b);if(c)this._adjustWindowElements(a,true);if(b=="AUTO")this.registerTimeoutHandler(1000,"_autoStopPlaying('"+a+"')",this);else if(b>0)this.registerTimeoutHandler(eval(b)*1000,"stopDisplay('"+a+"')",this)};RichMediaCreativeDisplayManager_60_15.prototype.tellCompanionAssetStop=function(a){this.dualAssetManager.tellCompanionAssetStop(a)};
RichMediaCreativeDisplayManager_60_15.prototype.tellCompanionAssetStart=function(a){this.dualAssetManager.tellCompanionAssetStart(a)};RichMediaCreativeDisplayManager_60_15.prototype.tellCompanionAssetHide=function(a){this.dualAssetManager.tellCompanionAssetHide(a)};RichMediaCreativeDisplayManager_60_15.prototype.tellCompanionAssetShow=function(a){this.dualAssetManager.tellCompanionAssetShow(a)};
RichMediaCreativeDisplayManager_60_15.prototype.getAsset=function(a){if(this.creative.assets["floatAssets"])for(var b=0;b<this.creative.assets["floatAssets"].length;b++){var c=this.creative.assets["floatAssets"][b];if(c.variableName==a)return c}else for(var d in this.creative.assets)if(!this.isPartOfArrayPrototype(d)&&this.creative.assets[d].variableName==a)return this.creative.assets[d];return null};
RichMediaCreativeDisplayManager_60_15.prototype.getHTML5Asset=function(){for(var a in this.creative.assets)if(!this.isPartOfArrayPrototype(a))return this.creative.assets[a];return null};RichMediaCreativeDisplayManager_60_15.prototype.tellAssetHide=function(a){var b=this.getAssetType(a);if(b==this.ASSET_TYPE_OVERLAY)this.closePopupAsset(a);else this.stopDisplay(a)};RichMediaCreativeDisplayManager_60_15.prototype.tellAssetShow=function(a){this._startDisplay(a,false)};
RichMediaCreativeDisplayManager_60_15.prototype.tellAssetStart=function(a){if(this.isFlashScriptingSupported())this.playFlash(a)};RichMediaCreativeDisplayManager_60_15.prototype.tellAssetStop=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())b.StopPlay()};RichMediaCreativeDisplayManager_60_15.prototype.tellAssetGotoFrame=function(a,b){var c=this.toObject("FLASH_"+a);if(c&&this.isFlashScriptingSupported())c.GotoFrame(b)};
RichMediaCreativeDisplayManager_60_15.prototype.isAssetPlaying=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())return b.IsPlaying();return false};
RichMediaCreativeDisplayManager_60_15.prototype.replayAsset=function(a){var b=this.toObject("DIV_"+a);if(b&&b.style.visibility!="visible"){b.style.visibility="visible";var c=this.getAsset(a);if(c!=null){var d=this.toObject("FLASH_"+a);d.Rewind();d.StopPlay();this.scheduleDisplay(a,c.duration,true);if(c.isMainAsset){var e=this.getRenderingId(a);this.logEvent("Start","DISPLAY_TIMER",e)}}}};
RichMediaCreativeDisplayManager_60_15.prototype.openPopup=function(a,b,c,d){if(c)var e=window.open(a,b,c);else e=window.open(a,b);this.dartPopupArray[b]=e;if(eval(d))window.focus();return e};
RichMediaCreativeDisplayManager_60_15.prototype.notifyPreviewHandler=function(a,b){if(this.creative.debugEventsMode&&this.previewHandler)try{if(b=="startDisplay"){var c=this.generateGlobalCallback("replayAsset('"+a.variableName+"')",this);this.previewHandler.onAssetDisplayed("DIV_"+a.variableName,a.assetType,c)}else if(b=="stopDisplay")this.previewHandler.onBeforeAssetRemoved("DIV_"+a.variableName,a.assetType)}catch(d){}};
RichMediaCreativeDisplayManager_60_15.prototype.stopDisplay=function(a){var b=this.toObject("DIV_"+a);if(b.style.visibility=="hidden")return;var c=this.getAsset(a);this.notifyPreviewHandler(c,"stopDisplay");var d=this.toObject("FLASH_"+a);if(!d)d=this.toObject("IFRAME_"+a);var e=this.creative.renderingId;if(c.isMainAsset&&!this.isAnyMainAssetPlaying(a))this.stopStandardTimers(e);this.flushCounters(e);if(!this.isAnyCompanionVisible(a))this.scheduleTurnOffEventBinFlushing(e,2);b.removeChild(d);b.style.visibility=
"hidden";this._adjustWindowElements(a,false)};RichMediaCreativeDisplayManager_60_15.prototype.isAnyMainAssetPlaying=function(a){for(var b in this.assets)if(!this.isPartOfArrayPrototype(b)&&b!=a){var c=this.toObject("DIV_"+b);if(c&&c.style.visibility=="visible"&&this.assets[b].isMainAsset)return true}return false};
RichMediaCreativeDisplayManager_60_15.prototype.isAnyCompanionVisible=function(a){for(var b in this.assets)if(!this.isPartOfArrayPrototype(b)&&b!=a){var c=this.toObject("DIV_"+b);if(c&&c.style.visibility=="visible")return true}return false};RichMediaCreativeDisplayManager_60_15.prototype.addEntityProperties=function(a,b,c,d,e,f,g){this.pageElementsManager.addEntityProperties(a,b,c,d,e,f,g)};
RichMediaCreativeDisplayManager_60_15.prototype.doNotAdjustIFrame=function(a,b){this.pageElementsManager.doNotAdjustIFrame(a,b)};RichMediaCreativeDisplayManager_60_15.prototype.doNotAdjustObject=function(a,b){this.pageElementsManager.doNotAdjustObject(a,b)};RichMediaCreativeDisplayManager_60_15.prototype.getRenderingId=function(a){var b=a.split("_");return b.length>1?b[0]:null};
RichMediaCreativeDisplayManager_60_15.prototype.createFunctionCall=function(a,b){var c=a+"(";var d=0;for(var e=0;e<b.length;e++){if(d>0)c+=", ";c+='"'+b[e]+'"';d++}c+=")";return c};RichMediaCreativeDisplayManager_60_15.prototype._splitArgs=function(a){var b=new Array;var c=unescape(a);var d=c.split("#mtf#");for(var e=0;e<d.length;e++)b[e]=d[e];return b};
RichMediaCreativeDisplayManager_60_15.prototype._parseCommandString=function(a){var b=new Object;b.command=unescape(a.split("=")[0]);b.argString=unescape(a.split("=")[1]);var c=b.argString.split("#mtf#");b.argArray=new Array;for(var d=0;d<c.length;d++)b.argArray[d]=c[d]=="null"?null:c[d];return b};
RichMediaCreativeDisplayManager_60_15.prototype._startDisplay=function(a,b){var c=this.toObject("DIV_"+a);var d=this.toObject("FLASH_"+a);if(b)this._adjustWindowElements(a,true);if(c)c.style.visibility="visible";if(d&&this.isFlashScriptingSupported())this.playFlash(a);var e=this.creative.renderingId;if(d&&this.debugEventsMode){if(!this.dartDebugEventBin.getShouldFlush(e)){this.setShouldFlush(e,true);this.dartDebugEventBin.flushMetCounters(e)}}else if(d&&!this.previewMode&&!this.dartEventBin.getShouldFlush(e))this.setShouldFlush(e,
true)};RichMediaCreativeDisplayManager_60_15.prototype.playFlash=function(a){var b=this.toObject("FLASH_"+a);var c=this.getAsset(a);var d=c.assetType;if(this.isInternetExplorer())b.Play();else if(d=="float"||d=="reminder"||d=="banner"||d=="expando")if(c.conduitInitialized){if(b.TCurrentFrame("/")<=0)b.Play()}else this.registerTimeoutHandler(100,"playFlash('"+a+"')",this)};
RichMediaCreativeDisplayManager_60_15.prototype._autoStopPlaying=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())if(b.PercentLoaded()==100&&!b.IsPlaying())this.stopDisplay(a);else this.registerTimeoutHandler(300,"_autoStopPlaying('"+a+"')",this)};RichMediaCreativeDisplayManager_60_15.prototype._adjustWindowElements=function(a,b){this.pageElementsManager._adjustWindowElements(a,b)};RichMediaCreativeDisplayManager_60_15.prototype.triggerPoliteDownload=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a))this.finishPoliteDownload(a)};
RichMediaCreativeDisplayManager_60_15.prototype.finishPoliteDownload=function(a){var b=this.toObject("FLASH_"+a);if(this.isFlashObjectReady(this.creative.asVersion,b,a))this.setFlashVariable(this.creative.asVersion,b,"mtfContinue","1");else{var c="dartCreativeDisplayManagers['"+this.creativeIdentifier+"'].finishPoliteDownload('"+a+"');";window.setTimeout(c,100)}};RichMediaCreativeDisplayManager_60_15.prototype.triggerDispatchScriptLoaded=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a))this.finishDispatchScriptLoaded(a)};
RichMediaCreativeDisplayManager_60_15.prototype.finishDispatchScriptLoaded=function(a){var b=this.toObject("FLASH_"+a);try{if(b&&typeof b.PercentLoaded!="undefined"&&b.PercentLoaded()>0&&typeof b.TCurrentFrame!="undefined"&&b.TCurrentFrame("/")>=0)this.setFlashVariable(this.creative.asVersion,b,"globalTemplateScriptLoaded","1");else{var c="dartCreativeDisplayManagers['"+this.creativeIdentifier+"'].finishDispatchScriptLoaded('"+a+"');";window.setTimeout(c,100)}}catch(d){c="dartCreativeDisplayManagers['"+
this.creativeIdentifier+"'].finishDispatchScriptLoaded('"+a+"');";window.setTimeout(c,100)}};RichMediaCreativeDisplayManager_60_15.prototype.unloadPopup=function(){var a=this.renderingId;if(a){this.flushCounters(a);this.stopStandardTimers(a)}};RichMediaCreativeDisplayManager_60_15.prototype.forceAnimation=function(a){var b=this.toObject("FLASH_"+a);var c=this.toObject("DIV_"+a);if(c.style.visibility=="visible"){b.Zoom(50);b.Zoom(0)}};
RichMediaCreativeDisplayManager_60_15.prototype.isFlashScriptingSupported=function(){return this.isWindows()||this.isMac()&&(this.isFirefox()||this.isSafari()||this.isChrome())};RichMediaCreativeDisplayManager_60_15.prototype.registerCreativeElement=function(a){this.rootElementArray[this.rootElementArray.length]=a};
RichMediaCreativeDisplayManager_60_15.prototype.removeChildNode=function(a,b){if(a.hasChildNodes()){var c=a.childNodes;for(var d=0;d<c.length;d++)this.removeChildNode(c[d],b)}else{var e=a.parentNode;e.removeChild(a);if(b!=e)this.removeChildNode(e,b)}};RichMediaCreativeDisplayManager_60_15.prototype.openPopupAsset=function(){if(this.overlay)this.overlay._openPopup()};RichMediaCreativeDisplayManager_60_15.prototype.closePopupAsset=function(){if(this.overlay)this.overlay._closePopup()};
RichMediaCreativeDisplayManager_60_15.prototype.registerOverlay=function(a){this.overlay=a};RichMediaCreativeDisplayManager_60_15.prototype.getAssetType=function(a){for(var b in this.creative.assets)if(this.creative.assets[b].variableName==a)return b;return null};RichMediaCreativeDisplayManager_60_15.prototype.setServedInIframe=function(a){this.servedInIframe=a};RichMediaCreativeDisplayManager_60_15.prototype.isServedInIframe=function(){return this.sourceIframe!=null};
RichMediaCreativeDisplayManager_60_15.prototype.setSourceIframe=function(a){this.sourceIframe=a};RichMediaCreativeDisplayManager_60_15.prototype.getSourceIframe=function(){return this.sourceIframe};
RichMediaCreativeDisplayManager_60_15.prototype.createHTML5AdIframe=function(a){var b="IFRAME_"+a.variableName;var c=document.createElement("IFRAME");c.id=b;c.src=a.url+"?liveEnvironment=true";c.scrolling="no";c.frameBorder="0";c.seamless=true;c.width=a.assetType=="Expanding"?a.expandedWidth:a.width;c.height=a.assetType=="Expanding"?a.expandedHeight:a.height;c.style.position="relative";c.style.top="0px";c.style.left="0px";c.style.width=(a.assetType=="Expanding"?a.expandedWidth:a.width)+"px";c.style.height=
(a.assetType=="Expanding"?a.expandedHeight:a.height)+"px";return c};RichMediaCreativeDisplayManager_60_15.prototype.invokeExternalJSFunction=function(a){if(this.creative.type!=this.CREATIVE_TYPE_EXPANDING)return;if(this.previewMode){var b=this.getEventBin();if(b!=null)b.logExternalJSFunctionCall(unescape(a),this.creative.renderingId)}else try{eval(unescape(a))}catch(c){}};RichMediaCreativeDisplayManager_60_15.prototype.setThrottlingWindow=function(a){var b=this.getEventBin();if(b!=null)if(this._isValidNumber(a))b.setMinimumFlushingDuration(parseFloat(a))};
RichMediaCreativeDisplayManager_60_15.prototype.logHTML5Impression=function(){var a=this.getEventBin();if(a){var b=this.getStandardEventId(this.STANDARD_EVENT_HTML5_CREATIVE_IMPRESSION);a.logMetEvent("Count",b,this.creative.renderingId,false,this.STANDARD_EVENT_HTML5_CREATIVE_IMPRESSION)}};RichMediaCreativeDisplayManager_60_15.prototype.attachMessageHandler=function(){self.addEventListener("message",this.bind(this,this.messageHandler),false)};
RichMediaCreativeDisplayManager_60_15.prototype.bind=function(a,b){var c=arguments.length>2?arguments.slice(2):[];return function(){return b.apply(a,arguments.slice?arguments.concat(c):arguments)}};RichMediaCreativeDisplayManager_60_15.prototype.messageHandler=function(a){var b=this.toObject(this.html5IframeId);if(b.contentWindow==a.source)this.messageCommandHandler(a)};
RichMediaCreativeDisplayManager_60_15.prototype.messageCommandHandler=function(a){var b=a.data;var c=this._parseCommandString(unescape(b));var d=this.createFunctionCall(c.command,c.argArray);try{eval('dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+d)}catch(e){}};
RichMediaCreativeDisplayManager_60_15.prototype.invokeEnablerFunction=function(a,b,c){var d={};d.methodName=a;if(b&&b.join&&b.length>0)b=b.join("#mtf#");d.args=b?b:null;var e=this.getAsset(c);var f=document.getElementById("IFRAME_"+c).contentWindow;var g=this.getSiteProtocol(e.url)+"//"+this.getSiteHost(e.url);if(f)f.postMessage(escape(this.serializeCommand(d)),g)};RichMediaCreativeDisplayManager_60_15.prototype.serializeCommand=function(a){return escape(a.methodName)+"="+escape(a.args)};
RichMediaCreativeDisplayManager_60_15.prototype.setAdParameters=function(){var a=this.getHTML5Asset();if(a!=null)this.invokeEnablerFunction("setAdParameters",a.queryString,a.variableName)};
function RichMediaEventBin_60_15(a,b,c){this.dartIntervalArray=b?new Array:new Array(10,20,50,120,240);this.dartEventBinCollection=new Array;this.dartRegistrationTime=null;this.dartMaxTimeMilliseconds=20*60*1000;this.dartCreativeIdentifier=a;this.timerAdjustments=new Array;this.lastEventFlushingTime=null;this.minimumFlushingDuration=5*1000;this.importantEventsArray=c;this.dynamicServeId=null}/*RichMediaEventBin_60_15.prototype=new RichMediaCore_60_15;*/
RichMediaEventBin_60_15.prototype.setTimerAdjustment=function(a,b,c){var d=new Object;d.eventId=a;d.startAdjustmentTime=parseInt(b);d.stopAdjustmentTime=parseInt(c);this.timerAdjustments[a]=d};
RichMediaEventBin_60_15.prototype.registerEventBinUrl=function(a,b){if(!this.dartEventBinCollection[a]){var c=new Array;c["counter"]=new Array;c["timer"]=new Array;c["duration"]=new Array;c["nonCumulativeCounters"]=new Array;c["flushUrl"]=b;c["shouldFlush"]=true;this.dartEventBinCollection[a]=c;this.dartRegistrationTime=new Date;this.setFlushInterval(a)}};RichMediaEventBin_60_15.prototype.setDynamicServeId=function(a){this.dynamicServeId=a};
RichMediaEventBin_60_15.prototype.logMetEvent=function(a,b,c,d){if(this.dartEventBinCollection[c]&&b&&!isNaN(b))switch(a){case "Count":{this.processCounter(b,c,d);break}case "Start":{this.processStart(b,c);break}case "Stop":{this.processStopTimer(b,c);break}default:break}};
RichMediaEventBin_60_15.prototype.processCounter=function(a,b,c){var d=this.getNonCumulativeCountersArray(b);var e=this.getCounterArray(b);c=c&&(c=="true"||c==true);if(!c){if(!d[a])e[a]=1;d[a]=true}else{if(!e[a])e[a]=0;e[a]=e[a]+1}};RichMediaEventBin_60_15.prototype.processStart=function(a,b){var c=this.getTimerArray(b);if(!c[a]){var d=new Date;var e=this.timerAdjustments[a];if(e){var f=d.getTime()+e.startAdjustmentTime;d.setTime(f)}c[a]=d;this.processCounter(a,b,false)}};
RichMediaEventBin_60_15.prototype.processStopTimer=function(a,b){var c=this.getTimerArray(b);var d=this.getDurationArray(b);if(c[a]){var e=c[a];var f=new Date;var g=f.getTime()-e.getTime();if(g<0||g>this.dartMaxTimeMilliseconds)g=0;d[a]=d[a]?d[a]+g:g;c[a]=false;return true}return false};RichMediaEventBin_60_15.prototype.shouldFlush=function(){var a=(new Date).getTime();return this.lastEventFlushingTime==null?true:a-this.lastEventFlushingTime>this.minimumFlushingDuration};
RichMediaEventBin_60_15.prototype.hasAnyImportantEventPending=function(a){var b=this.getCounterArray(a);for(var c in b)if(!this.isPartOfArrayPrototype(c)&&b[c]>0)for(var d=0;d<this.importantEventsArray.length;d++)if(c==this.importantEventsArray[d])return true;return false};
RichMediaEventBin_60_15.prototype.flushMetCounters=function(a){if(this.dartEventBinCollection[a]&&this.getShouldFlush(a)){var b="";var c=this.getCounterArray(a);var d=this.getDurationArray(a);var e=this.getTimerArray(a);var f=1;if((this.shouldFlush()||this.hasAnyImportantEventPending(a))&&this.isInAllowedTimeframe()){for(var g in c)if(!this.isPartOfArrayPrototype(g)){var h=this.processStopTimer(g,a);var i=c[g];if(!d[g])d[g]=0;var j=this.roundNumber(d[g]?parseFloat(String(d[g]/1000)):0);if(i>0||j>
0){b+="eid"+f+"="+g+";";b+="ecn"+f+"="+i+";";b+="etm"+f+"="+j+";"}c[g]=c[g]-i;d[g]=d[g]-j*1000;if(h)e[g]=new Date;f++}this.lastEventFlushingTime=(new Date).getTime();this.postData(b,a)}}};RichMediaEventBin_60_15.prototype.turnOffFlushing=function(a){this.flushMetCounters(a);this.setMetShouldFlush(false)};
RichMediaEventBin_60_15.prototype.postData=function(a,b){if(a.length){var c=new Date;var d=this.splitActivity(a);for(var e=0;e<d.length;e++){var f=document.createElement("img");var g=d[e];f.src=this.getFlushUrl(b)+this.getDynamicServeKeyvalue()+"&timestamp="+c.getTime()+";"+g}}};RichMediaEventBin_60_15.prototype.getDynamicServeKeyvalue=function(){return this.dynamicServeId?"rm_mid="+escape(this.dynamicServeId)+";":""};
RichMediaEventBin_60_15.prototype.splitActivity=function splitActivity(b){var c=new Array;var d="etm";var e=950;for(var f=0;b.length>0;b=b.substr(f)){var g=b;var h=g.substr(0,e);f=h.lastIndexOf(d)+d.length;h=g.substr(0,f);g=g.substr(f);f+=g.indexOf(";")+1;c[c.length]=b.substr(0,f)}return c};RichMediaEventBin_60_15.prototype.getCounterArray=function(a){var b=this.dartEventBinCollection[a];return b["counter"]};
RichMediaEventBin_60_15.prototype.getTimerArray=function(a){var b=this.dartEventBinCollection[a];return b["timer"]};RichMediaEventBin_60_15.prototype.getDurationArray=function(a){var b=this.dartEventBinCollection[a];return b["duration"]};RichMediaEventBin_60_15.prototype.getNonCumulativeCountersArray=function(a){var b=this.dartEventBinCollection[a];return b["nonCumulativeCounters"]};RichMediaEventBin_60_15.prototype.getFlushUrl=function(a){var b=this.dartEventBinCollection[a];return b["flushUrl"]};
RichMediaEventBin_60_15.prototype.getShouldFlush=function(a){var b=this.dartEventBinCollection[a];return b["shouldFlush"]};RichMediaEventBin_60_15.prototype.setMetShouldFlush=function(a,b){var c=this.dartEventBinCollection[a];if(c)c["shouldFlush"]=b};RichMediaEventBin_60_15.prototype.isInAllowedTimeframe=function(){var a=new Date;return!(a.getTime()-this.dartRegistrationTime.getTime()>this.dartMaxTimeMilliseconds)};
RichMediaEventBin_60_15.prototype.roundNumber=function(a,b){b=b?b:0;return Math.round(a*Math.pow(10,b))/Math.pow(10,b)};RichMediaEventBin_60_15.prototype.setFlushInterval=function(a){for(var b=0;b<this.dartIntervalArray.length;b++){var c=this.dartIntervalArray[b]*1000;this.registerTimeoutHandler(c,"flushMetCounters('"+a+"')",this)}};RichMediaEventBin_60_15.prototype.setMinimumFlushingDuration=function(a){this.minimumFlushingDuration=a*1000};
function MSNAdListener_60_15(a){this.asset=a;this.init()}/*MSNAdListener_60_15.prototype=new RichMediaCore_60_15;*/MSNAdListener_60_15.prototype.init=function(){var a=this.getAssetOffset();try{$WLXRmAd.init({width:parseFloat(this.asset.width),height:parseFloat(this.asset.height),offsetLeft:a.offsetLeft,offsetRight:a.offsetRight,offsetTop:a.assetTop,offsetBottom:a.offsetBottom})}catch(b){}};
MSNAdListener_60_15.prototype.getAssetOffset=function(){var a=new Object;a.offsetLeft=parseFloat(this.asset.offsetLeft)==0?0:parseFloat(this.asset.offsetLeft);a.offsetRight=parseFloat(this.asset.expandedWidth)==parseFloat(this.asset.offsetRight)?0:parseFloat(this.asset.expandedWidth)-parseFloat(this.asset.offsetRight);a.offsetTop=parseFloat(this.asset.offsetTop)==0?0:parseFloat(this.asset.offsetTop);a.offsetBottom=parseFloat(this.asset.expandedHeight)==parseFloat(this.asset.offsetBottom)?0:parseFloat(this.asset.expandedHeight)-
parseFloat(this.asset.offsetBottom);return a};MSNAdListener_60_15.prototype.expand=function(){try{$WLXRmAd.expand()}catch(a){}};MSNAdListener_60_15.prototype.collapse=function(){try{$WLXRmAd.collapse()}catch(a){}};function YahooAdListener_60_15(a){this.asset=a;this.init()}/*YahooAdListener_60_15.prototype=new RichMediaCore_60_15;*/YahooAdListener_60_15.prototype.init=function(){try{Y.SandBox.vendor.register(parseFloat(this.asset.width),parseFloat(this.asset.height))}catch(a){}};
YahooAdListener_60_15.prototype.getAssetOffset=function(){var a=new Object;a.offsetX=parseFloat(this.asset.offsetLeft)==0?parseFloat(this.asset.expandedWidth)-parseFloat(this.asset.width):-(parseFloat(this.asset.expandedWidth)-parseFloat(this.asset.width));a.offsetY=parseFloat(this.asset.offsetTop)==0?parseFloat(this.asset.expandedHeight)-parseFloat(this.asset.height):-(parseFloat(this.asset.expandedHeight)-parseFloat(this.asset.height));return a};
YahooAdListener_60_15.prototype.expand=function(){var a=this.getAssetOffset();try{Y.SandBox.vendor.expand(a.offsetX,a.offsetY)}catch(b){}};YahooAdListener_60_15.prototype.collapse=function(){try{Y.SandBox.vendor.collapse()}catch(a){}};function PageElementsManager_60_15(a,b){this.creative=a;this.displayManager=b;this.dartEntityPropertiesArray=new Object;this.noAdjustElements=new _doNotAdjustElement;this.iframePlaceHolderDivIndex=0;this.hiddenIframes=new Array}/*PageElementsManager_60_15.prototype=new RichMediaCore_60_15;*/
PageElementsManager_60_15.prototype.addEntityProperties=function(a,b,c,d,e,f,g){this.dartEntityPropertiesArray[a]=new _entityProperties(b,c,d,e,f,g)};PageElementsManager_60_15.prototype.doNotAdjustIFrame=function(a,b){this.noAdjustElements.iFrames[this.noAdjustElements.iFrames.length]=b};PageElementsManager_60_15.prototype.doNotAdjustObject=function(a,b){this.noAdjustElements.objects[this.noAdjustElements.objects.length]=b};
PageElementsManager_60_15.prototype._adjustWindowElements=function(a,b){var c=this.dartEntityPropertiesArray[a];if(c){if(c.hideDropDowns)this._adjustElements(b,"select");if(c.hideScrollBars&&(this.isInternetExplorer()||this.isSafari()))this.adjustScrollbars(b);if(c.hideIFrames)this._adjustElements(b,"iframe");if(c.hideObjects){this._adjustElements(b,"object");this._adjustElements(b,"embed")}if(c.hideApplets)this._adjustElements(b,"applet");if(c.adjustZIndex)this._adjustZIndex(a,b)}};
PageElementsManager_60_15.prototype._adjustZIndex=function(a,b){try{this._adjustParentZIndex(a,b)}catch(c){}};
PageElementsManager_60_15.prototype._adjustParentZIndex=function(a,b){var c=this.toObject("DIV_"+a);var d=null;var e=this.displayManager.getAsset(a);if(c&&typeof e.assetType!="undefined"&&e.assetType==this.ASSET_TYPE_EXPANDING)d=c.parentNode.parentNode;else return;for(;d&&d.tagName!="BODY";){if(b){var f=this.getStyle(d);if(c.style.zIndex>f.zIndex&&(f.position=="relative"||f.position=="absolute")){d.style.originalZIndex=this.getStyle(d).zIndex;d.style.zIndex=c.style.zIndex}}else if(typeof d.style.originalZIndex!=
"undefined")d.style.zIndex=d.style.originalZIndex;d=d.parentNode}};PageElementsManager_60_15.prototype._adjustElements=function(a,b){var c=self.document.getElementsByTagName(b);b=b.toLowerCase();for(var d=0;d<c.length;d++){var e=true;if(b=="iframe")if(typeof c[d].MotifIFrameIDArray!="undefined")e=this._shouldAdjustIFrame(c[d].MotifIFrameIDArray);else e=!this.isHTML5ContainerIframe(c[d].id);else if(b=="object"||b=="embed")e=!this.isMotifObject(c[d].id);if(e)a?this.hideElement(c[d]):this.showElement(c[d])}};
PageElementsManager_60_15.prototype.hideElement=function(a){var b=a.getAttribute("hideCount");if(b==null||b==""){a.setAttribute("initialVisibility",a.style.visibility);a.setAttribute("hideCount",0);if(!a.getAttribute("hideCount")){a.initialVisibility=a.style.visibility;a.hideCount=0}}var c=parseInt(a.getAttribute("hideCount"));if(c==0)if(a.tagName.toLowerCase()=="iframe"&&this.isFirefox())this.hideFirefoxIFrame(a);else a.style.visibility="hidden";c++;a.setAttribute("hideCount",c);if(!a.getAttribute("hideCount"))a.hideCount=
c};PageElementsManager_60_15.prototype.showElement=function(a){if(a.getAttribute("hideCount")!=null){var b=parseInt(a.getAttribute("hideCount"));if(b!=0)b--;a.setAttribute("hideCount",b);if(!a.getAttribute("hideCount"))a.hideCount=b;if(b==0)if(a.tagName.toLowerCase()=="iframe"&&this.isFirefox())this.displayFirefoxIFrame(a);else a.style.visibility=a.getAttribute("initialVisibility")}};
PageElementsManager_60_15.prototype._shouldAdjustIFrame=function(a){var b=this.noAdjustElements.iFrames;for(var c=0;c<b.length;c++)for(var d=0;d<a.length;d++)if(b[c]==a[d])return false;return true};
PageElementsManager_60_15.prototype.isMotifObject=function(a){for(var b=0;b<dartMotifAds.length;b++){var c=dartMotifAds[b];if(c.assets["floatAssets"])for(b=0;b<c.assets["floatAssets"].length;b++){var d=c.assets["floatAssets"][b];if(a=="FLASH_"+d.variableName)return true}else for(var e in c.assets)if(a=="FLASH_"+c.assets[e].variableName)return true}return false};
PageElementsManager_60_15.prototype.isHTML5ContainerIframe=function(a){for(var b=0;b<dartMotifAds.length;b++){var c=dartMotifAds[b];for(var d in c.assets)if(a=="IFRAME_"+c.assets[d].variableName)return true}return false};function _entityProperties(a,b,c,d,e,f){this.hideDropDowns=a;this.hideIFrames=b;this.hideScrollBars=c;this.hideObjects=d;this.hideApplets=e;this.adjustZIndex=f}function _doNotAdjustElement(){this.iFrames=new Array;this.objects=new Array}
PageElementsManager_60_15.prototype.hideFirefoxIFrame=function(a){var b=null;var c=null;if(!a.hasAttribute("Motif_IFramePlaceHolderDivIndex")){b=document.createElement("DIV");b.id="MOTIF_IFRAMEPLACEHOLDER_"+this.iframePlaceHolderDivIndex;b.style.width="0px";b.style.height="0px";b.style.visibility="hidden";b.style.padding="0px";b.style.margin="0px";b.style.display="inline";a.parentNode.insertBefore(b,a);b.innerHTML='<img src="" width="0px" height="0px" padding="0px" margin="0px"></img>';a.setAttribute("Motif_IFramePlaceHolderDivIndex",
this.iframePlaceHolderDivIndex);c=new Object;this.hiddenIframes[this.iframePlaceHolderDivIndex]=c;this.iframePlaceHolderDivIndex++}else{var d=a.getAttribute("Motif_IFramePlaceHolderDivIndex");var e="MOTIF_IFRAMEPLACEHOLDER_"+d;b=document.getElementById(e);c=this.hiddenIframes[parseInt(d)]}c.width=a.width;c.height=a.height;b.style.width=c.width;b.style.height=c.height;b.firstChild.width=c.width;b.firstChild.height=c.height;a.style.visibility="hidden";a.width=0;a.height=0};
PageElementsManager_60_15.prototype.displayFirefoxIFrame=function(a){var b=a.getAttribute("Motif_IFramePlaceHolderDivIndex");var c="MOTIF_IFRAMEPLACEHOLDER_"+b;var d=document.getElementById(c);var e=this.hiddenIframes[parseInt(b)];if(d!=null){a.width=e.width;a.height=e.height;d.style.width="0px";d.style.height="0px";d.firstChild.width=0;d.firstChild.height=0}a.style.visibility=a.getAttribute("initialVisibility")};
PageElementsManager_60_15.prototype.adjustScrollbars=function(a){var b=self.document.documentElement;var c=document.compatMode&&document.compatMode=="CSS1Compat";c|=this.isSafari();if(a)if(c){b.style.originalOverflow=typeof b.currentStyle=="object"?b.currentStyle.overflow:b.style.overflow;b.style.overflow="hidden"}else self.document.body.scroll="no";else if(c){if(typeof b.style.originalOverflow!="undefined")b.style.overflow=b.style.originalOverflow}else self.document.body.scroll="yes"};
function ExpandingManager_60_15(a,b){this.creative=a;this.displayManager=b;this.init()}/*ExpandingManager_60_15.prototype=new RichMediaCore_60_15;*/
ExpandingManager_60_15.prototype.init=function(){if(this.isInAdSenseIFrame()){this.creativeToolset=new CreativeToolset;var a=this.creative.assets[this.ASSET_TYPE_EXPANDING];var b="dartCallbackObjects["+this.getCallbackObjectIndex(this)+"].adSenseExpand(expandedWidth, expandedHeight, direction)";var c=new Function("expandedWidth","expandedHeight","direction",b);var d="dartCallbackObjects["+this.getCallbackObjectIndex(this)+"].adSenseCollapse(collapsedWidth, collapsedHeight)";var e=new Function("collapsedWidth",
"collapsedHeight",d);var f=parseInt(a.offsetLeft)+parseInt(a.width);var g=parseInt(a.expandedWidth)-parseInt(a.offsetLeft);var h=parseInt(a.offsetTop)+parseInt(a.height);var i=parseInt(a.expandedHeight)-parseInt(a.offsetTop);var j={width:Math.max(f,g),height:Math.max(h,i),expansionCallback:c,collapseCallback:e};this.creativeToolset.enableExpansion(j)}if(this.isInWinLiveAPIPlatform())this.displayManager.adListener=new MSNAdListener_60_15(this.creative.assets[this.ASSET_TYPE_EXPANDING]);else if(this.isInYahooCrossDomainIframe())this.displayManager.adListener=
new YahooAdListener_60_15(this.creative.assets[this.ASSET_TYPE_EXPANDING])};ExpandingManager_60_15.prototype.adSenseExpand=function(a,b,c){try{var d=["tl","tr","br","bl"];var e=this.toObject("FLASH_"+this.creative.assets[this.ASSET_TYPE_EXPANDING].variableName);this.setFlashVariable(this.creative.asVersion,e,"mde_expandedDirection",d[c])}catch(f){}};
ExpandingManager_60_15.prototype.adSenseCollapse=function(a,b){try{var c=this.toObject("FLASH_"+this.creative.assets[this.ASSET_TYPE_EXPANDING].variableName);this.setFlashVariable(this.creative.asVersion,c,"mde_expandedState","collapsed")}catch(d){}};ExpandingManager_60_15.prototype.getPosition=function(a,b){return"position:absolute;"+"top:"+(0-a)+"px;"+"left:"+(0-b)+"px;"};
ExpandingManager_60_15.prototype.startAnimation=function(a,b,c){if(a.animationState==null){var d=new Object;d.isRunning=false;d.animateCallback=this.generateGlobalCallback('updateExpandingViewPort("'+a.variableName+'", '+c+")",this);d.expandMode=true;var e=parseInt(a.height);d.currentHeight=e;var f=parseInt(a.expandedHeight);var g=f-e;var h=a.animationTime*1000;d.updateInterval=50;var i=Math.ceil(h/d.updateInterval);d.stepLength=Math.ceil(g/(i+1));a.animationState=d}a.animationState.expandMode=b;
if(!a.animationState.isRunning){a.animationState.isRunning=true;this.updateExpandingViewPort(a.variableName,c)}};
ExpandingManager_60_15.prototype.updateExpandingViewPort=function(a,b){var c=this.displayManager.getAsset(a);var d=c.animationState;var e=false;var f="auto";var g="auto";var h="auto";if(d.expandMode){var i=parseInt(c.expandedHeight);d.currentHeight+=d.stepLength;if(d.currentHeight>=i){d.currentHeight=i;e=true}}else{var j=parseInt(c.height);f=c.offsetTop;g=c.offsetRight;h=c.offsetLeft;d.currentHeight-=d.stepLength;if(d.currentHeight<=j){d.currentHeight=j;e=true}}var k=this.toObject("EXPANDO_PLACEHOLDER_"+
a);k.style.height=d.currentHeight+"px";var l=f=="auto"?c.expandedWidth:c.width;this.displayManager.clipFlashObject(c,l,d.currentHeight,f,g,d.currentHeight,h,b);if(e)d.isRunning=false;else window.setTimeout(d.animateCallback,d.updateInterval)};
ExpandingManager_60_15.prototype.getExpandingDirection=function(a){var b=this.getElementPosition(this.toObject("OUTER_DIV_"+a.variableName));var c=this.getWindowDimension();var d=this.getAvailableVeticalDirection(c.height,b.top,a.height);var e=this.getAvailableHorizontalDirection(c.width,b.left,a.width);return d+e};ExpandingManager_60_15.prototype.getAvailableVeticalDirection=function(a,b,c){var d=a-(b+parseInt(c));return b>=d?"t":"b"};
ExpandingManager_60_15.prototype.getAvailableHorizontalDirection=function(a,b,c){var d=a-(b+parseInt(c));return b>=d?"l":"r"};ExpandingManager_60_15.prototype.isMultiDirectionalExpanding=function(a){try{return this.getFlashVariable(this.creative.asVersion,a,"isMultiDirectional")=="true"}catch(b){return false}};
ExpandingManager_60_15.prototype.adjustParentOverflow=function(a,b){for(;a;){if(a.tagName!="BODY"){var c=this.getStyle(a);if(c.overflow=="hidden"||c.overflowX&&c.overflowX=="hidden"||c.overflowY&&c.overflowY=="hidden")if(this.shouldAdjustOverflow(a,b))a.style.overflow="visible"}if(a.tagName=="BODY")break;a=a.parentNode}};
ExpandingManager_60_15.prototype.shouldAdjustOverflow=function(a,b){var c=this.getElementPosition(this.toObject("OUTER_DIV_"+b.variableName));var d=this.getElementPosition(a);if(b.width!=b.expandedWidth){var e=parseInt(c.left)-parseInt(d.left);var f=parseInt(a.offsetWidth)-(parseInt(e)+parseInt(b.width));var g=this.getAssetEdgePosition(b.offsetLeft,b.offsetRight,b.expandedWidth);if(e<g.x||f<g.y)return true}if(b.height!=b.expandedHeight){var h=parseInt(c.top)-parseInt(d.top);var i=parseInt(a.offsetHeight)-
(parseInt(h)+parseInt(b.height));var j=this.getAssetEdgePosition(b.offsetTop,b.offsetBottom,b.expandedHeight);if(h<j.x||i<j.y)return true}return false};ExpandingManager_60_15.prototype.getAssetEdgePosition=function(a,b,c){var d=new Object;d.x=a=="0"?0:parseInt(a);d.y=b==c?0:parseInt(c)-parseInt(b);return d};function ScriptExpandingRenderer_60_15(a){this.flashUtil=new FlashUtil_60_15(a)}/*ScriptExpandingRenderer_60_15.prototype=new RichMediaCore_60_15;*/
ScriptExpandingRenderer_60_15.prototype.renderFlashExpanding=function(a,b){var c=a.assets[this.ASSET_TYPE_EXPANDING];var d=b.getPosition(c.offsetTop,c.offsetLeft);var e="dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onMouseOut('"+c.variableName+"');";var f="dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onMouseOver('"+c.variableName+"');";var g=c.expandingDivStyleSheet!=""?c.expandingDivStyleSheet+";":"";var h=this.getClipStyleOnCollapsedState(c);document.write('<div id="DIV_'+
c.variableName+'" style="'+d+"visibility:visible;z-index:"+c.zIndex+";clip:"+h+";text-align:left;"+g+'">');var i=c.queryString;i+="&td="+escape(self.location.hostname)+"&wmode="+c.wmode;i+=b.usesSalignForExpanding(c.salign,c.wmode)?"&scaleMode=noScale":"";i+="&ispushdown="+c.pushContents;var j=this.flashUtil.getObjectHtml("id","FLASH_"+c.variableName,"name","FLASH_"+c.variableName,"WIDTH",c.expandedWidth,"HEIGHT",c.expandedHeight,"movie",c.url,"quality","high","wmode",c.wmode,"salign",c.salign,"queryString",
i,"onmouseover",f,"onmouseout",e);/*RichMediaCore_60_15.prototype.trackCsiEvent("fb");*/document.write(j);document.write("</div>")};
ScriptExpandingRenderer_60_15.prototype.renderHtml5Expanding=function(a,b,c){var d=a.assets[this.ASSET_TYPE_EXPANDING];var e=c.getPosition(d.offsetTop,d.offsetLeft);var f="dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onMouseOutHtml5('"+d.variableName+"');";var g="dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onMouseOverHtml5('"+d.variableName+"');";var h="dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onTouchEndHtml5('"+d.variableName+"');";var i="dartCreativeDisplayManagers['"+
a.creativeIdentifier+"'].onTouchHtml5('"+d.variableName+"');";var j=d.expandingDivStyleSheet!=""?d.expandingDivStyleSheet+";":"";var k="IFRAME_"+d.variableName;document.write('<div id="DIV_'+d.variableName+'"onmouseover="'+g+'" ontouchstart="'+i+'" onmouseout="'+f+'" ontouchend="'+h+'" style="'+e+"visibility:visible;z-index:"+d.zIndex+";text-align:left;"+j+";width:"+d.expandedWidth+"px;height:"+d.expandedHeight+'px;">');document.write("<iframe id='"+k+"' src='"+d.url+"?liveEnvironment=true' allowtransparency='"+
d.allowtransparency+"' style='position:relative;top:0px;left:0px;width:"+d.expandedWidth+"px;height:"+d.expandedHeight+"px;' width='"+d.expandedWidth+"px' height='"+d.expandedHeight+"px' frameborder='0' scrolling='no'></iframe>");document.write("</div>");b.html5IframeId=k;b.attachMessageHandler();b.registerUrl(a.renderingId,a.adserverUrl);b.logHTML5Impression()};
ScriptExpandingRenderer_60_15.prototype.displayExpanding=function(a,b,c){var d=a.assets[this.ASSET_TYPE_EXPANDING];var e=d.expandingDivStyleSheet!=""?";"+d.expandingDivStyleSheet:"";var f="";var g=d.pushContents&&this.isInternetExplorer()&&this.getIEVersion()>=8;if(d.displayInline&&!g)f=this.isSafari()||this.isChrome()?"display:inline-table;":"display:inline;";var h=d.displayInline?e:";"+d.cssProperty;document.write('<table style="'+f+"width:"+d.width+"px;height:"+d.height+"px"+h+'" border="0" cellpadding="0" cellspacing="0"> ');
document.write('<tr style="padding:0px;margin:0px;border-style:none;border-width:0px">');document.write('<td style="padding:0px;margin:0px;border-style:none;border-width:0px">');document.write('<div id="OUTER_DIV_'+d.variableName+'" style="position:relative;z-index:'+d.zIndex+e+'">');document.write('<IMG id="'+"EXPANDO_PLACEHOLDER_"+d.variableName+'" SRC="'+a.mediaServer+'/dot.gif" style="visibility:hidden" width="'+d.width+'" height="'+d.height+'" BORDER="0" alt="">');if(a.shouldDisplayHTML5Asset)this.renderHtml5Expanding(a,
b,c);else{this.renderFlashExpanding(a,c);this.logThirdPartyFlashDisplayImpression(a,false)}document.write("</div>");document.write("</td> </tr> </table>");this.startDisplay(a,b);c.adjustParentOverflow(this.toObject("OUTER_DIV_"+d.variableName),d)};
ScriptExpandingRenderer_60_15.prototype.startDisplay=function(a,b){var c=a.assets[this.ASSET_TYPE_EXPANDING];if(!a.shouldDisplayHTML5Asset){b.doNotAdjustObject(c.variableName,"FLASH_"+c.variableName);b.fsHook("FLASH_"+c.variableName);b.registerUrl(a.renderingId,a.adserverUrl)}b.addEntityProperties(c.variableName,c.hideDropdowns,c.hideIframes,c.hideScrollbars,c.hideObjects,c.hideApplets,true);b.collapseAsset(c.variableName)};
ScriptExpandingRenderer_60_15.prototype.getClipStyleOnCollapsedState=function(a){var b=this.checkDimension(a.offsetTop);var c=this.checkDimension(a.offsetRight);var d=this.checkDimension(a.offsetBottom);var e=this.checkDimension(a.offsetLeft);return"rect("+b+" "+c+" "+d+" "+e+")"};function FlashUtil_60_15(a){this.creative=a}/*FlashUtil_60_15.prototype=new RichMediaCore_60_15;*/
FlashUtil_60_15.prototype.getObjectHtml=function(){var a=this.getArgs(arguments);return this.generateObj(a.objAttrs,a.params,a.embedAttrs)};
FlashUtil_60_15.prototype.getArgs=function(a){var b=new Object;b.embedAttrs=new Object;b.params=new Object;b.objAttrs=new Object;var c="";var d=false;for(var e=0;e<a.length;e=e+2){var f=a[e].toLowerCase();switch(f){case "codebase":case "pluginspage":case "type":case "classid":case "minversion":break;case "src":case "movie":b.params["movie"]=b.embedAttrs["src"]=a[e+1];break;case "querystring":c=a[e+1]=a[e+1]+"&br="+escape(this.getBrowser())+"&os="+escape(this.getOS());break;case "width":case "height":case "align":case "vspace":case "hspace":case "class":case "title":case "accesskey":case "name":case "id":case "tabindex":case "alt":case "onmouseover":case "onmouseout":b.embedAttrs[a[e]]=
b.objAttrs[a[e]]=a[e+1];break;case "swliveconnect":b.embedAttrs[a[e]]=a[e+1];break;case "wmode":d=this.isFlashFullScreenSupported(a[e+1]);b.embedAttrs[a[e]]=b.params[a[e]]=a[e+1];break;default:b.embedAttrs[a[e]]=b.params[a[e]]=a[e+1]}}c+="&isFlashFullScreenEnabled="+d;b.params["FlashVars"]=b.embedAttrs["FlashVars"]=c;b.objAttrs["classid"]="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";b.embedAttrs["type"]="application/x-shockwave-flash";b.params["allowScriptAccess"]="always";b.embedAttrs["allowScriptAccess"]=
"always";if(d){b.params["allowFullScreen"]="true";b.embedAttrs["allowFullScreen"]="true"}return b};
FlashUtil_60_15.prototype.generateObj=function(a,b,c){var d="";if(this.isInternetExplorer()){d+="<object ";for(var e in a)if(!this.isPartOfArrayPrototype(e))d+=e+'="'+a[e]+'" ';d+=">";for(e in b)if(!this.isPartOfArrayPrototype(e))d+='<param name="'+e+'" value="'+b[e]+'" /> '}d+="<embed ";for(e in c)if(!this.isPartOfArrayPrototype(e))d+=e+'="'+c[e]+'" ';d+=" />";if(this.isInternetExplorer())d+="</object>";return d};
FlashUtil_60_15.prototype.getBrowser=function(){if(this.isInternetExplorer())return"ie";else if(this.isFirefox())return"ff";else if(this.isSafari())return"sf";else if(this.isChrome())return"cr";else return"NOT_SUPPORTED"};FlashUtil_60_15.prototype.getOS=function(){if(this.isWindows())return"win";if(this.isMac())return"mac";if(this.isAndroid())return"android";else return"NOT_SUPPORTED"};
FlashUtil_60_15.prototype.isFlashFullScreenSupported=function(a){var b=this.getPluginInfo();var c=this.creative.requiredPlayerVersion;if(c>5&&this.creative.fullScreenEnabled)if(b>=9.115||b>=9.28&&a=="window")return true;return false};function ScriptCreativeRenderer_60_15(){}/*ScriptCreativeRenderer_60_15.prototype=new RichMediaCore_60_15;*/
ScriptCreativeRenderer_60_15.prototype.showCreative=function(a){a.isProcessed=true;var b=a.type;var c=new RichMediaCreativeDisplayManager_60_15(a);dartCreativeDisplayManagers[a.creativeIdentifier]=c;if(b==this.CREATIVE_TYPE_INPAGE){var d=new InpageRenderer_60_15(a);d.displayInpage(a,c)}else if(b==this.CREATIVE_TYPE_EXPANDING){d=new ScriptExpandingRenderer_60_15(a);var e=new ExpandingManager_60_15(a,c);e.init();c.setExpandingManager(e);d.displayExpanding(a,c,e)}else if(b==this.CREATIVE_TYPE_FLOATING){var f=
a.assets[this.ASSET_TYPE_FLOATING];var g=new FloatingManager_60_15(a,c);if(this._isValidStartTime(f.startTime))c.registerTimeoutHandler(eval(f.startTime)*1000,"displayFloatingFlash()",g)}else if(b==this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY){var h=new InpageRenderer_60_15(a);h.displayInpage(a,c);var i=new RichMediaOverlay_60_15(a,c);c.registerOverlay(i);i.scheduleOverlay()}else if(b==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING){h=new InpageRenderer_60_15(a);h.displayInpage(a,c);f=a.assets[this.ASSET_TYPE_FLOATING];
g=new FloatingManager_60_15(a,c);c.setFloatingManager(g);if(this._isValidStartTime(f.startTime))c.registerTimeoutHandler(eval(f.startTime)*1000,"displayFloatingFlash()",g)}else if(b==this.CREATIVE_TYPE_MULTI_FLOATING){g=new FloatingManager_60_15(a,c);for(var j=0;j<a.assets["floatAssets"].length;j++){f=a.assets["floatAssets"][j];if(this._isValidStartTime(f.startTime))c.registerTimeoutHandler(eval(f.startTime)*1000,"displayFloatingFlash('"+f.variableName+"')",g)}}if(!a.shouldDisplayHTML5Asset&&c.isFlashScriptingSupported()){c.scheduleCallbackOnLoad("triggerPoliteDownload()");
c.triggerDispatchScriptLoaded()}};ScriptCreativeRenderer_60_15.prototype.showOnPageLoad=function(a){var b=dartRichmediaCreatives[a];this.showCreative(b)};
ScriptCreativeRenderer_60_15.prototype.isGlobalTemplateCompatible=function(a){var b="expanding";if(a.globalTemplateVersion!="60_15")return false;switch(a.type){case this.CREATIVE_TYPE_FLOATING:return b=="floating";case this.CREATIVE_TYPE_EXPANDING:return b=="expanding";case this.CREATIVE_TYPE_INPAGE:return b=="inpage";case this.CREATIVE_TYPE_INPAGE_WITH_FLOATING:return b=="inpageFloating";case this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY:return b=="inpageOverlay";case this.CREATIVE_TYPE_MULTI_FLOATING:return b==
"floating";default:return false}};ScriptCreativeRenderer_60_15.prototype.show=function(){this.registerPageLoadHandler("pageLoaded()",this);for(var a=0;a<dartRichmediaCreatives.length;a++){var b=dartRichmediaCreatives[a];if(typeof b.isProcessed=="undefined"||!b.isProcessed)if(this.isGlobalTemplateCompatible(b))if(b.type==this.CREATIVE_TYPE_FLOATING||b.type==this.CREATIVE_TYPE_MULTI_FLOATING)this.registerPageLoadHandler("showOnPageLoad("+a+")",this);else this.showCreative(b)}};
if(dartRichmediaCreatives!=undefined)(new ScriptCreativeRenderer_60_15).show();/*RichMediaCore_60_15.prototype.trackCsiEvent("ge");*/}}