if(typeof dartCallbackObjects=="undefined")var dartCallbackObjects=new Array;if(typeof dartCreativeDisplayManagers=="undefined")var dartCreativeDisplayManagers=new Object;if(typeof dartMotifAds=="undefined")var dartMotifAds=new Array;if(!self.dartLoadedGlobalTemplates_60_10)self.dartLoadedGlobalTemplates_60_10={};if(self.dartLoadedGlobalTemplates_60_10["expandingIframe"])self.dartLoadedGlobalTemplates_60_10["expandingIframe"].isLoaded=true;
function RichMediaCore_60_10(){this.CREATIVE_TYPE_EXPANDING="ExpandingFlash";this.CREATIVE_TYPE_FLOATING="FloatingFlash";this.CREATIVE_TYPE_INPAGE="InpageFlash";this.CREATIVE_TYPE_MULTI_FLOATING="MultiFloatingFlash";this.CREATIVE_TYPE_INPAGE_WITH_FLOATING="InpageFlashFloatingFlash";this.CREATIVE_TYPE_FLOATING_WITH_REMINDER="FloatingFlashReminderFlash";this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY="InpageFlashOverlayFlash";this.ASSET_TYPE_FLOATING="Floating";this.ASSET_TYPE_INPAGE="Inpage";this.ASSET_TYPE_EXPANDING=
"Expanding";this.ASSET_TYPE_REMINDER="Reminder";this.ASSET_TYPE_OVERLAY="Overlay";this.STANDARD_EVENT_DISPLAY_TIMER="DISPLAY_TIMER";this.STANDARD_EVENT_INTERACTION_TIMER="INTERACTION_TIMER";this.STANDARD_EVENT_INTERACTIVE_IMPRESSION="EVENT_USER_INTERACTION";this.STANDARD_EVENT_FULL_SCREEN_VIDEO_PLAYS="";this.STANDARD_EVENT_FULL_SCREEN_VIDEO_COMPLETES="";this.STANDARD_EVENT_FULL_SCREEN_AVERAGE_VIEW_TIME="";this.STANDARD_EVENT_MANUAL_CLOSE="EVENT_MANUAL_CLOSE";this.STANDARD_EVENT_BACKUP_IMAGE="BACKUP_IMAGE_IMPRESSION";
this.STANDARD_EVENT_EXPAND_TIMER="EXPAND_TIMER";this.STANDARD_EVENT_VIDEO_PLAY="EVENT_VIDEO_PLAY";this.STANDARD_EVENT_VIDEO_VIEW_TIMER="EVENT_VIDEO_VIEW_TIMER";this.STANDARD_EVENT_VIDEO_VIEW_COMPLETE="EVENT_VIDEO_COMPLETE";this.STANDARD_EVENT_VIDEO_INTERACTION="EVENT_VIDEO_INTERACTION";this.STANDARD_EVENT_VIDEO_PAUSE="EVENT_VIDEO_PAUSE";this.STANDARD_EVENT_VIDEO_MUTE="EVENT_VIDEO_MUTE";this.STANDARD_EVENT_VIDEO_REPLAY="EVENT_VIDEO_REPLAY";this.STANDARD_EVENT_VIDEO_MIDPOINT="EVENT_VIDEO_MIDPOINT";
this.STANDARD_EVENT_VIDEO_FULLSCREEN="";this.STANDARD_EVENT_VIDEO_STOP="EVENT_VIDEO_STOP";this.STANDARD_EVENT_VIDEO_UNMUTE="EVENT_VIDEO_UNMUTE";this.STANDARD_EVENT_FULLSCREEN="EVENT_FULLSCREEN";this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION="DYNAMIC_CREATIVE_IMPRESSION";this.STANDARD_EVENT_HTML5_CREATIVE_IMPRESSION="HTML5_CREATIVE_IMPRESSION"}RichMediaCore_60_10.prototype.isPageLoaded=false;RichMediaCore_60_10.prototype.csiTimes=new Object;
RichMediaCore_60_10.prototype.setCsiEventsRecordedDuringBreakout=function(a){if(a.gtStartLoadingTime!=undefined)this.csiTimes["gb"]=a.gtStartLoadingTime};RichMediaCore_60_10.prototype.csiHasValidStart=function(a){return a.csiAdRespTime>=0&&a.csiAdRespTime<100000};RichMediaCore_60_10.prototype.shouldReportCsi=function(a){return this.csiHasValidStart(a)||Math.floor(Math.random()*1001)==1};
RichMediaCore_60_10.prototype.shouldCsi=function(a,b){switch(b){case this.CREATIVE_TYPE_INPAGE_WITH_FLOATING:return a.assetType==this.ASSET_TYPE_INPAGE;case this.CREATIVE_TYPE_FLOATING_WITH_REMINDER:return a.assetType==this.ASSET_TYPE_FLOATING;case this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY:return a.assetType==this.ASSET_TYPE_INPAGE;default:return true}};RichMediaCore_60_10.prototype.trackCsiEvent=function(a){this.csiTimes[a]=(new Date).getTime()};
RichMediaCore_60_10.prototype.getCsiServer=function(){return self.location.protocol&&self.location.protocol.toString().toLowerCase()=="https:"?"https://static.doubleclick.net":"http://static.2mdn.net"};
RichMediaCore_60_10.prototype.reportCsi=function(a){if(!a.previewMode&&this.shouldReportCsi(a)){var b=this.getCsiServer()+"/csi/d?s=rmad&v=2&rt=";var c="";var d="";for(var e in this.csiTimes){var f=this.csiTimes[e]-a.csiBaseline;b+=e+"."+(f>0?f:0)+",";if(e=="pb"||e=="gb"||e=="fb")c+=e+"."+(f>0?f:0)+","}b=b.replace(/\,$/,"");var g=this.csiTimes["pe"]-this.csiTimes["pb"];var h=this.csiTimes["ge"]-this.csiTimes["gb"];var i=this.csiTimes["fe"]-this.csiTimes["fb"];d="pl."+(g>0?g:0)+","+"gl."+(h>0?h:0)+
","+"fl."+(i>0?i:0);b+="&irt="+c.replace(/\,$/,"")+"&it="+d;var j=new RegExp(/(.*\/\/)/);b+="&adi=asd_"+a.adServer.replace(j,"")+",csd_"+a.mediaServer.replace(j,"")+",gt_"+a.globalTemplateJs.replace(/(.*\/)/,"");if(this.csiHasValidStart(a))b+="&srt="+a.csiAdRespTime;this.trackUrl(b,true,a.previewMode)}};RichMediaCore_60_10.prototype._isValidStartTime=function(a){return this._isValidNumber(a)};
RichMediaCore_60_10.prototype._convertDuration=function(a){if(a){a=a.toString().toUpperCase();switch(a){case "AUTO":return"AUTO";case "NONE":return 0;default:return this._isValidNumber(a)?eval(a):0}}return 0};RichMediaCore_60_10.prototype.convertUnit=function(a){if(a!=""){a=a.toLowerCase().replace(new RegExp("pct","g"),"%");if(a.indexOf("%")<0&&a.indexOf("px")<0&&a.indexOf("pxc")<0)a+="px"}return a};
RichMediaCore_60_10.prototype._isValidNumber=function(a){var b=parseFloat(a);if(isNaN(b)||b<0)return false;return b==a};RichMediaCore_60_10.prototype.writeSurveyURL=function(a){if(!a.previewMode&&a.surveyUrl.length>0)document.write("<scr"+'ipt src="'+a.surveyUrl+'" language="JavaScript"></scr'+"ipt>")};RichMediaCore_60_10.prototype.postPublisherData=function(a,b){if(!a.previewMode&&this.isInterstitialCreative(a)&&b!=""){var c=new Image;c.src=b}};
RichMediaCore_60_10.prototype.isInterstitialCreative=function(a){return a.type==this.CREATIVE_TYPE_FLOATING||a.type==this.CREATIVE_TYPE_FLOATING_WITH_REMINDER};RichMediaCore_60_10.prototype.isBrowserComplient=function(a){return(this.isAndroid()&&this.getAndroidOSVersion()>2.1||(this.isInternetExplorer()||this.isFirefox()||this.isSafari()||this.isChrome())&&(this.isWindows()||this.isMac()))&&a>0&&this.getPluginInfo()>=a};
RichMediaCore_60_10.prototype.shouldDisplayFloatingAsset=function(a){return!this.isInternetExplorer()||this._convertDuration(a)||this.getIEVersion()>=5.5};RichMediaCore_60_10.prototype.isWindows=function(){return navigator.appVersion.indexOf("Windows")!=-1};
RichMediaCore_60_10.prototype.isFirefox=function(){var a=navigator.userAgent.toUpperCase();if(a.indexOf("GECKO")!=-1)if(a.indexOf("FIREFOX")!=-1){var b=parseFloat(a.substr(a.lastIndexOf("/")+1));return b>=1}else if(a.indexOf("NETSCAPE")!=-1){b=parseFloat(a.substr(a.lastIndexOf("/")+1));return b>=8}else return false;else return false};
RichMediaCore_60_10.prototype.isSafari=function(){var a="Safari";var b=navigator.userAgent.indexOf(a);var c=navigator.vendor!=undefined?navigator.vendor.toUpperCase():"";return navigator.appVersion.indexOf(a)!=-1&&parseFloat(navigator.userAgent.substring(b+a.length+1))>=312.6&&(c.indexOf("APPLE")!=-1||this.isAndroid()&&c.indexOf("GOOGLE")!=-1)};
RichMediaCore_60_10.prototype.isChrome=function(){var a=navigator.userAgent.toUpperCase();var b=navigator.vendor!=undefined?navigator.vendor.toUpperCase():"";return a.indexOf("CHROME")!=-1&&b.indexOf("GOOGLE")!=-1};RichMediaCore_60_10.prototype.isMac=function(){return navigator.appVersion.indexOf("Mac")!=-1};RichMediaCore_60_10.prototype.isInternetExplorer=function(){return navigator.appVersion.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Opera")<0};
RichMediaCore_60_10.prototype.isIPhone=function(){return navigator.userAgent.toUpperCase().indexOf("IPHONE")!=-1};RichMediaCore_60_10.prototype.isIPad=function(){return navigator.userAgent.toUpperCase().indexOf("IPAD")!=-1};RichMediaCore_60_10.prototype.isAndroid=function(){return navigator.userAgent.toUpperCase().indexOf("ANDROID")!=-1};
RichMediaCore_60_10.prototype.getAndroidOSVersion=function(){var a=navigator.userAgent.toUpperCase().indexOf("ANDROID");var b=navigator.userAgent.substring(a+"ANDROID".length+1);return parseFloat(b)};RichMediaCore_60_10.prototype.getAndroidBrowserVersion=function(){var a=navigator.userAgent.toUpperCase().indexOf("VERSION");var b=navigator.userAgent.substring(a+"VERSION".length+1);return parseFloat(b)};
RichMediaCore_60_10.prototype.getIEVersion=function(){var a=0;if(this.isInternetExplorer()){var b="MSIE ";var c=navigator.appVersion.indexOf(b)+b.length;var d=navigator.appVersion.substr(c);a=parseFloat(d.substring(0,d.indexOf(";")))}return a};RichMediaCore_60_10.prototype.getFirefoxVersion=function(){var a=navigator.userAgent.toUpperCase().indexOf("FIREFOX")+"FIREFOX".length+1;return parseFloat(navigator.userAgent.substring(a))};
RichMediaCore_60_10.prototype.getSafariVersion=function(){var a=navigator.userAgent.toUpperCase().indexOf("VERSION")+"VERSION".length+1;return parseFloat(navigator.userAgent.substring(a))};RichMediaCore_60_10.prototype.getChromeVersion=function(){var a=navigator.userAgent.toUpperCase().indexOf("CHROME")+"CHROME".length+1;return parseFloat(navigator.userAgent.substring(a))};RichMediaCore_60_10.prototype.isHTML5SupportedBrowser=function(){return!!document.createElement("canvas").getContext};
RichMediaCore_60_10.prototype.getPluginInfo=function(){return this.isInternetExplorer()&&this.isWindows()?this._getIeWindowsFlashPluginVersion():this._detectNonWindowsFlashPluginVersion()};
RichMediaCore_60_10.prototype._detectNonWindowsFlashPluginVersion=function(){var a=0;var b="Shockwave Flash";if(navigator.plugins&&(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins[b])){var c=navigator.plugins["Shockwave Flash 2.0"]?" 2.0":"";var d=navigator.plugins[b+c].description;var e=d.indexOf(b)+(b.length+1);var f=d.indexOf(".");var g=d.substring(e,f);var h=d.split(" ");var i=parseInt(h[h.length-1].replace(new RegExp("[A-Za-z]","g"),""));if(isNaN(i))i="0";a=parseFloat(g+"."+i);if(a>
6&&a<6.65)a=0}return a};
RichMediaCore_60_10.prototype._getIeWindowsFlashPluginVersion=function(){var a="";var b=0;var c=new Array;var d=new Array;var e="\r\n";var f=0;var g="swfVersion = "+f+e+"mtfIsOk = "+false+e+"On Error Resume Next"+e+'set motifSwfObject = CreateObject("ShockwaveFlash.ShockwaveFlash")'+e+"mtfIsOk = IsObject(motifSwfObject)"+e+"if mtfIsOk = true then"+e+'swfVersion = motifSwfObject.GetVariable("$version")'+e+"end if"+e+"";window.execScript(g,"VBScript");if(mtfIsOk){a=swfVersion;d=a.split(" ");if(d.length>
1){c=d[1].split(",");var h=c[0];var i=c[2];if(h>9&&c.length>3)i=c[c.length-1];b=parseFloat(h+"."+i)}}return b};RichMediaCore_60_10.prototype.trackBackupImageEvent=function(a){var b="eid1=9;ecn1=1;etm1=0;";var c=new Date;var d=document.createElement("IMG");d.src=a+"&timestamp="+c.getTime()+";"+b};
RichMediaCore_60_10.prototype.trackUrl=function(a,b,c){if(c||a=="")return;if(b){var d=document.createElement("IMG");d.style.visibility="hidden";d.style.width="0px";d.style.height="0px";d.src=a;d.onload=function(){this.parentNode.removeChild(this)};document.body.appendChild(d)}else document.write('<IMG SRC="'+a+'" style="display:none" onload="this.parentNode.removeChild(this)" width="0px" height="0px" alt="">')};
RichMediaCore_60_10.prototype.logThirdPartyImpression=function(a){this.trackUrl(a.thirdPartyImpUrl,false,a.previewMode)};RichMediaCore_60_10.prototype.logThirdPartyBackupImageImpression=function(a,b){this.trackUrl(a.thirdPartyBackupImpUrl,b,a.previewMode)};RichMediaCore_60_10.prototype.logThirdPartyFlashDisplayImpression=function(a,b){this.trackUrl(a.thirdPartyFlashDisplayUrl,b,a.previewMode)};
RichMediaCore_60_10.prototype.isPartOfArrayPrototype=function(a){for(var b in Array.prototype)if(b==a)return true;return false};RichMediaCore_60_10.prototype.toObject=function(a){try{if(document.layers)return document.layers[a]?eval(document.layers[a]):null;else if(document.all&&!document.getElementById)return eval("window."+a)?eval("window."+a):null;else if(document.getElementById&&document.body.style)return document.getElementById(a)?eval(document.getElementById(a)):null}catch(b){}return null};
RichMediaCore_60_10.prototype.getCallbackObjectIndex=function(a){for(var b=0;b<dartCallbackObjects.length;b++)if(dartCallbackObjects[b]==a)return b;dartCallbackObjects[dartCallbackObjects.length]=a;return dartCallbackObjects.length-1};
RichMediaCore_60_10.prototype.registerPageLoadHandler=function(a,b){var c=this.generateGlobalCallback(a,b);if(document.readyState&&document.readyState=="complete"||this.isFirefox()&&this.isPageLoaded){c();return}if(this.isInternetExplorer())self.attachEvent("onload",c);else self.addEventListener("load",c,true)};RichMediaCore_60_10.prototype.pageLoaded=function(){RichMediaCore_60_10.prototype.isPageLoaded=true};
RichMediaCore_60_10.prototype.registerPageUnLoadHandler=function(a,b){var c=this.generateGlobalCallback(a,b);if(this.isInternetExplorer()&&this.isWindows())self.attachEvent("onunload",c);else if(this.isFirefox()||this.isSafari()||this.isChrome())self.addEventListener("unload",c,true)};RichMediaCore_60_10.prototype.registerTimeoutHandler=function(a,b,c){window.setTimeout(this.generateGlobalCallback(b,c),a)};
RichMediaCore_60_10.prototype.createFunction=function(a,b,c){var d="dartCallbackObjects["+this.getCallbackObjectIndex(b)+"]."+a+"(";for(var e=0;e<c.length;e++){d+="dartCallbackObjects["+this.getCallbackObjectIndex(c[e])+"]";if(e!=c.length-1)d+=","}d+=")";return new Function(d)};RichMediaCore_60_10.prototype.generateGlobalCallback=function(a,b){if(b){var c=this.getCallbackObjectIndex(b);a="if(dartCallbackObjects["+c+"] != null) dartCallbackObjects["+c+"]."+a}return new Function(a)};
RichMediaCore_60_10.prototype.registerEventHandler=function(a,b,c,d){var e=this.generateGlobalCallback(c,d);if(this.isInternetExplorer()&&this.isWindows())self.attachEvent("on"+a,e);else if(this.isFirefox()||this.isSafari()||this.isChrome())b.addEventListener(a,e,false)};RichMediaCore_60_10.prototype.scheduleCallbackOnLoad=function(a){var b=200;if(window.document.readyState.toLowerCase()=="complete")eval(a);else this.registerTimeoutHandler(b,"scheduleCallbackOnLoad('"+a+"')",this)};
RichMediaCore_60_10.prototype.getStyle=function(a){if(window.getComputedStyle)return window.getComputedStyle(a,"");else if(a.currentStyle)return a.currentStyle;else return a.style};
RichMediaCore_60_10.prototype.getWindowDimension=function(){var a=new Object;if(document.documentElement&&document.compatMode=="CSS1Compat"){a.width=document.documentElement.clientWidth;a.height=document.documentElement.clientHeight}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)&&!this.isSafari()){a.width=document.body.clientWidth;a.height=document.body.clientHeight}else if(typeof window.innerWidth=="number"){a.width=window.innerWidth;a.height=window.innerHeight}return a};
RichMediaCore_60_10.prototype.getScrollbarPosition=function(){var a=new Object;a.scrollTop=0;a.scrollLeft=0;if(typeof window.pageYOffset=="number"){a.scrollTop=window.pageYOffset;a.scrollLeft=window.pageXOffset}else if(document.body&&(document.body.scrollLeft||document.body.scrollTop)){a.scrollTop=document.body.scrollTop;a.scrollLeft=document.body.scrollLeft}else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)){a.scrollTop=document.documentElement.scrollTop;
a.scrollLeft=document.documentElement.scrollLeft}return a};RichMediaCore_60_10.prototype.isInFriendlyIFrame=function(){return this.isWindowAccessible(self.parent)};RichMediaCore_60_10.prototype.isWindowAccessible=function(a){try{a.document.body;return true}catch(b){return false}};RichMediaCore_60_10.prototype.isInMsnFriendlyIFrame=function(){return typeof inDapIF!="undefined"&&inDapIF};RichMediaCore_60_10.prototype.isInAolFriendlyIFrame=function(){return typeof inFIF!="undefined"&&inFIF};
RichMediaCore_60_10.prototype.isInMsnAjaxEnvironment=function(){return typeof inDapMgrIf!="undefined"&&inDapMgrIf};RichMediaCore_60_10.prototype.isInYahooFriendlyIFrame=function(){return typeof isAJAX!="undefined"&&isAJAX};RichMediaCore_60_10.prototype.isInClientPreviewIFrame=function(){if(typeof StudioPreviewResponse!="undefined")return!(new StudioPreviewResponse).isAdslotDetected;else return false};
RichMediaCore_60_10.prototype.isInAdSenseIFrame=function(){return typeof IN_ADSENSE_IFRAME!="undefined"&&IN_ADSENSE_IFRAME};RichMediaCore_60_10.prototype.isInWinLiveAPIPlatform=function(){try{return window["$WLXRmAd"]||window.parent&&window.parent["$WLXRmAd"]}catch(a){return false}};RichMediaCore_60_10.prototype.isInYahooCrossDomainIframe=function(){try{return window.Y&&Y.SandBox?Y.SandBox.vendor||null:null}catch(a){return false}};
RichMediaCore_60_10.prototype.checkDimension=function(a){if(typeof a=="number")return a+"px";else return a+(a!=""&&a!="auto"&&a.indexOf("px")<0?"px":"")};RichMediaCore_60_10.prototype.setFlashVariable=function(a,b,c,d){if(a==1)b.SetVariable("_root."+c,d);else b.changeInputVariable(c,d)};RichMediaCore_60_10.prototype.getFlashVariable=function(a,b,c){if(a==1)return b.GetVariable("_root."+c);else return b.getFlashVariable(c)};
RichMediaCore_60_10.prototype.getSalign=function(a,b,c,d,e,f){var g="";if(c==0&&f!=b)g+="T";else if(c!=0&&f==b)g+="B";if(d==0&&e!=a)g+="L";else if(d!=0&&e==a)g+="R";if((g=="T"||g=="B")&&(d!=0||e!=a))return"";if((g=="L"||g=="R")&&(c!=0||f!=b))return"";return g};RichMediaCore_60_10.prototype.usesSalignForExpanding=function(a,b){return(this.isMac()&&(this.isSafari()||this.isFirefox())||this.isWindows()&&this.isFirefox()&&b.toLowerCase()=="window")&&a.length>0};
RichMediaCore_60_10.prototype.unclipFlashObject=function(a,b,c,d){this.clipFlashObject(a,b,c,"auto","auto","auto","auto",d)};
RichMediaCore_60_10.prototype.clipFlashObject=function(a,b,c,d,e,f,g,h){b=this.checkDimension(b);c=this.checkDimension(c);d=this.checkDimension(d);e=this.checkDimension(e);f=this.checkDimension(f);g=this.checkDimension(g);var i=this.isMac()&&this.isSafari();if(h||!(i&&a.pushContents)&&this.usesSalignForExpanding(a.salign,a.wmode)){var j=(h?"IFRAME_":"FLASH_")+a.variableName;var k=this.toObject(j);k.style.width=b;k.style.height=c;k.width=b;k.height=c;k.style.marginLeft=g=="auto"?"0px":g;k.style.marginTop=
d=="auto"?"0px":d}var l=this.toObject("DIV_"+a.variableName);if(l){if(i){l.style.height=c;l.style.width=b}l.style.clip="rect("+d+" "+e+" "+f+" "+g+")"}if(a.pushContents&&this.getIEVersion()>=8)this.redrawIE8ForPushdown()};RichMediaCore_60_10.prototype.redrawIE8ForPushdown=function(){var a=document.body.style.display;document.body.style.display="block";document.body.style.display=a};
RichMediaCore_60_10.prototype.getSitePageUrl=function(a){if(a.type==this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY)return"";if(a.previewMode)return a.livePreviewSiteUrl;else if(a.type==this.CREATIVE_TYPE_INPAGE&&a.servingMethod=="i")return self.document.referrer;else return self.location.href};
RichMediaCore_60_10.prototype.getElementPosition=function(a){var b=this.toObject(a);var c=new Object;if(b.getBoundingClientRect){c.left=b.getBoundingClientRect().left;c.top=b.getBoundingClientRect().top}else{c.left=0;c.top=0;if(b.offsetParent){do{c.left+=b.offsetLeft;c.top+=b.offsetTop}while(b=b.offsetParent)}var d=this.getScrollbarPosition();c.top-=d.scrollTop;c.left-=d.scrollLeft}return c};
RichMediaCore_60_10.prototype.isFlashObjectReady=function(a,b,c){if(a==1)return b&&typeof b.PercentLoaded!="undefined"&&b.PercentLoaded()>0&&this.getAsset(c).conduitInitialized;else return b!=null&&typeof b.changeInputVariable!="undefined"};RichMediaCore_60_10.prototype.getSiteHost=function(a){var b="";if(a.length>=7&&a.substr(0,7)=="http://")b=a.substr(7);else if(a.length>=8&&a.substr(0,8)=="https://")b=a.substr(8);else b=a;var c=b.indexOf("/");if(c>0)b=b.substr(0,c);return b};
RichMediaCore_60_10.prototype.getSiteProtocol=function(a){var b="";if(a.length>=5&&a.substr(0,5)=="http:")b="http:";else if(a.length>=6&&a.substr(0,6)=="https:")b="https:";else b="http:";return b};
function RichMediaCreativeDisplayManager_60_10(a,b){this.creative=a;this.creativeIdentifier=a.creativeIdentifier;this.previewMode=a.previewMode;this.debugEventsMode=a.debugEventsMode;this.renderingId=a.renderingId;this.creativeType=a.type;this.mtfNoFlush=a.mtfNoFlush;this.dartPopupArray=new Object;this.isDisplayTimerRunning=false;this.fsCommandHandlers=new Object;this.rootElementArray=new Array;this.sourceIframe=typeof b!="undefined"?b:null;this.overlay=null;this.dartEventBin=null;this.previewHandler=
null;this.importantEventArray=new Array(this.STANDARD_EVENT_INTERACTIVE_IMPRESSION,this.STANDARD_EVENT_VIDEO_PLAY,this.STANDARD_EVENT_VIDEO_VIEW_COMPLETE,this.STANDARD_EVENT_EXPAND_TIMER,this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION);this.adListener=null;this.init(a);dartMotifAds[dartMotifAds.length]=this.creative}RichMediaCreativeDisplayManager_60_10.prototype=new RichMediaCore_60_10;
RichMediaCreativeDisplayManager_60_10.prototype.init=function(a){this.buildImportantEventList(a);this.createEventBin(a);this.assets=new Object;if(this.creative.assets["floatAssets"])for(var b=0;b<this.creative.assets["floatAssets"].length;b++){var c=this.creative.assets["floatAssets"][b];this.assets[c.variableName]=c}else for(var d in this.creative.assets)if(!this.isPartOfArrayPrototype(d)){c=this.creative.assets[d];this.assets[c.variableName]=c}if(a.type==this.CREATIVE_TYPE_FLOATING_WITH_REMINDER||
a.type==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING||a.type==this.CREATIVE_TYPE_MULTI_FLOATING||a.type==this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY)this.dualAssetManager=new DualAssetManager_60_10(a,this);if(a.type==this.CREATIVE_TYPE_EXPANDING||a.type==this.CREATIVE_TYPE_FLOATING||a.type==this.CREATIVE_TYPE_FLOATING_WITH_REMINDER||a.type==this.CREATIVE_TYPE_MULTI_FLOATING||a.type==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING)this.pageElementsManager=new PageElementsManager_60_10(a,this)};
RichMediaCreativeDisplayManager_60_10.prototype.buildImportantEventList=function(a){for(var b=0;b<this.importantEventArray.length;b++)this.importantEventArray[b]=this.getStandardEventId(this.importantEventArray[b]);for(var c in a.videoComponents)if(!this.isPartOfArrayPrototype(c)){this.importantEventArray[this.importantEventArray.length]=this.getCustomVideoEventId("Count",c,this.STANDARD_EVENT_VIDEO_PLAY);this.importantEventArray[this.importantEventArray.length]=this.getCustomVideoEventId("Count",
c,this.STANDARD_EVENT_VIDEO_VIEW_COMPLETE)}for(var d in a.exitEvents)if(!this.isPartOfArrayPrototype(d))this.importantEventArray[this.importantEventArray.length]=this.getEventId("Exit",d)};
RichMediaCreativeDisplayManager_60_10.prototype.createEventBin=function(a){if(!this.previewMode)this.dartEventBin=new RichMediaEventBin_60_10(this.creativeIdentifier,this.mtfNoFlush,this.importantEventArray);else if(this.debugEventsMode){this.initDebugHandler(a);var b=this.getSourceIframe();if(typeof DebugEventBin_60_10!="undefined")this.dartDebugEventBin=new DebugEventBin_60_10(this.creativeIdentifier,this.previewHandler);else if(this.isServedInIframe()&&typeof b.contentWindow.DebugEventBin_60_10!=
"undefined")this.dartDebugEventBin=new b.contentWindow.DebugEventBin_60_10(this.creativeIdentifier,this.previewHandler)}};RichMediaCreativeDisplayManager_60_10.prototype.initDebugHandler=function(a){try{if(typeof DARTDebugEventHandler!="undefined")this.previewHandler=new DARTDebugEventHandler;else if(typeof self.parent.DARTDebugEventHandler!="undefined"){self.parent.globalTemplatePreviewHandler=new self.parent.DARTDebugEventHandler;this.previewHandler=self.parent.globalTemplatePreviewHandler}}catch(b){}};
RichMediaCreativeDisplayManager_60_10.prototype.deleteCreative=function(a){this.deleteJSObjects();if(!a)this.deleteHTMLObjects()};RichMediaCreativeDisplayManager_60_10.prototype.deleteHTMLObjects=function(){for(var a=0;a<this.rootElementArray.length;a++)if(this.rootElementArray[a]!=null&&this.rootElementArray[a].parentNode!=null)this.removeChildNode(this.rootElementArray[a],this.rootElementArray[a].parentNode)};
RichMediaCreativeDisplayManager_60_10.prototype.deleteJSObjects=function(){if(this.creative.isInterstitial)DoNotDisplayIA=null;this.detachFSCommandHandler();this.setShouldFlush(this.renderingId,false);this.removeArrayElement(dartCallbackObjects,this.dartEventBin);this.dartEventBin=null};RichMediaCreativeDisplayManager_60_10.prototype.removeArrayElement=function(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)a[c]=null};
RichMediaCreativeDisplayManager_60_10.prototype.fsHook=function(a){var b="";b+=a+"_DoFSCommand = function(command, args) { \n";b+='    if(dartCreativeDisplayManagers["'+this.creativeIdentifier+'"] != null) dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].FSCommandHandler(command, args);\n';b+="}\n";window.eval(b);if(this.isInternetExplorer()){var c=this.toObject(a);var d=eval(a+"_DoFSCommand");this.fsCommandHandlers[a]=d;if(c.attachEvent("FSCommand",d))this.registerPageUnLoadHandler("detachFSCommandHandler()",
this)}};RichMediaCreativeDisplayManager_60_10.prototype.registerFSCommandHandler=function(a){if(this.isInternetExplorer()){var b=this.toObject("FLASH_"+a);var c=this.fsCommandHandlers["FLASH_"+a];if(b.attachEvent("FSCommand",c))this.registerPageUnLoadHandler("detachFSCommandHandler()",this)}};
RichMediaCreativeDisplayManager_60_10.prototype.detachFSCommandHandler=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a)){var b="FLASH_"+a;var c=this.toObject(b);var d=this.fsCommandHandlers[b];if(c!=null)if(this.isInternetExplorer())c.detachEvent("FSCommand",d)}};
RichMediaCreativeDisplayManager_60_10.prototype.FSCommandHandler=function(a,b){if(a=="mtfCommands"){var c=b.split("&");for(var d=0;d<c.length;d++){var e=this._parseCommandString(c[d]);var f=this.createFunctionCall(e.command,e.argArray);try{eval('dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+f)}catch(g){f=e.command+"('"+e.argString+"')";try{eval(f)}catch(h){}}}}else{var i=this._splitArgs(b);f=this.createFunctionCall(a,i);try{return eval('dartCreativeDisplayManagers["'+this.creativeIdentifier+
'"].'+f)}catch(j){try{eval(f)}catch(k){}}}};RichMediaCreativeDisplayManager_60_10.prototype.setFocus=function(a){var b=this.toObject("FLASH_"+a);if(b!=null)if(this.isFirefox()&&this.isMac()){var c=this.getFireFoxVersion();if(c>=2&&c<3){b.blur();window.blur()}}};
RichMediaCreativeDisplayManager_60_10.prototype.reportCustomVariable=function(a,b){if(!this.previewMode){var c=this.creative.stringPostingUrl;var d=new Date;c+="&timestamp="+d.getTime()+";"+"str="+unescape(a)+";"+"strtype="+b;var e=document.createElement("img");e.src=c}else{var f=this.getEventBin();if(f!=null)f.logCustomVariable(unescape(a),b,this.creative.renderingId)}};
RichMediaCreativeDisplayManager_60_10.prototype.setDynamicServeId=function(a){var b=this.getEventBin();if(b){b.setDynamicServeId(a);var c=this.getStandardEventId(this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION);b.logMetEvent("Count",c,this.creative.renderingId,false,this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION);b.flushMetCounters(this.creative.renderingId)}};
RichMediaCreativeDisplayManager_60_10.prototype.getFireFoxVersion=function(){var a=navigator.userAgent.toUpperCase();if(a.indexOf("GECKO")!=-1)if(a.indexOf("FIREFOX")!=-1)return parseFloat(a.substr(a.lastIndexOf("/")+1));return null};
RichMediaCreativeDisplayManager_60_10.prototype.conduitInitialized=function(a){if(this.creative.shouldDisplayHTML5Asset)this.setAdParameters();else{RichMediaCore_60_10.prototype.trackCsiEvent("fe");var b=this.getAsset(a);b.conduitInitialized=true;if(this.shouldCsi(b,this.creative.type))RichMediaCore_60_10.prototype.reportCsi(this.creative)}};RichMediaCreativeDisplayManager_60_10.prototype.setTimerAdjustment=function(a,b,c){this.getEventBin().setTimerAdjustment(a,b,c)};
RichMediaCreativeDisplayManager_60_10.prototype.getEventBin=function(){if(!this.previewMode)return this.dartEventBin;else if(this.debugEventsMode)return this.dartDebugEventBin;else return null};RichMediaCreativeDisplayManager_60_10.prototype.getStandardEventId=function(a){return this.creative.standardEvents[a].reportingId};
RichMediaCreativeDisplayManager_60_10.prototype.getEventId=function(a,b){var c;if(a=="Start"||a=="Stop")c=this.creative.timerEvents[b];else if(a=="Count")c=this.creative.counterEvents[b];else if(a=="Exit")c=this.creative.exitEvents[b];return c!=null?c.reportingId:-1};RichMediaCreativeDisplayManager_60_10.prototype.evaluateBoolean=function(a){var b=typeof a;return b=="string"&&a=="true"||b=="boolean"&&a};
RichMediaCreativeDisplayManager_60_10.prototype.logEvent=function(a,b,c,d,e){var f;b=unescape(b);e=this.evaluateBoolean(e);d=this.evaluateBoolean(d);if(e)f=this.getEventId(a,b);else f=this.getStandardEventId(b);if(f==-1)return;if(a==="Exit")a="Count";if(b==this.STANDARD_EVENT_DISPLAY_TIMER)this.logDisplayTimerEvent(a,c);else{var g=this.getEventBin();if(g)g.logMetEvent(a,f,c,d,b)}};
RichMediaCreativeDisplayManager_60_10.prototype.getCustomVideoEventId=function(a,b,c){var d=this.getStandardEventId(c);var e;if(a=="Start"||a=="Stop")e=this.creative.timerEvents;else e=this.creative.counterEvents;var f="";for(var g in e){var h=e[g];if(h.sourceComponentName==b&&h.sourceStandardEventId==d){f=h.reportingId;break}}return f};
RichMediaCreativeDisplayManager_60_10.prototype.logVideoEvent=function(a,b,c){b=unescape(b);var d=this.creative.videoComponents[b];var e=this.getEventBin();var f=this.getStandardEventId(c);if(e)e.logMetEvent(a,f,this.creative.renderingId,false,c);if(d.trackCustomEvents){var g=this.getCustomVideoEventId(a,b,c);if(e)e.logMetEvent(a,g,this.creative.renderingId,false,c)}};
RichMediaCreativeDisplayManager_60_10.prototype.stopStandardTimers=function(a){this.logEvent("Stop",this.STANDARD_EVENT_DISPLAY_TIMER,a);this.logEvent("Stop",this.STANDARD_EVENT_INTERACTION_TIMER,a);this.logEvent("Stop",this.STANDARD_EVENT_VIDEO_VIEW_TIMER,a)};
RichMediaCreativeDisplayManager_60_10.prototype.logDisplayTimerEvent=function(a,b){var c=this.getEventBin();if(a=="Start"){if(!this.isDisplayTimerRunning){if(c)c.logMetEvent("Start","2",b);this.isDisplayTimerRunning=true}}else if(a=="Stop")if(this.isDisplayTimerRunning){if(c)c.logMetEvent("Stop","2",b);this.isDisplayTimerRunning=false}};RichMediaCreativeDisplayManager_60_10.prototype.flushCounters=function(a){var b=this.getEventBin();if(b)b.flushMetCounters(a)};
RichMediaCreativeDisplayManager_60_10.prototype.scheduleTurnOffEventBinFlushing=function(a,b){var c=this.getEventBin();if(c)this.registerTimeoutHandler(b*1000,"turnOffFlushing('"+a+"')",c)};RichMediaCreativeDisplayManager_60_10.prototype.setShouldFlush=function(a,b){var c=this.getEventBin();if(c)c.setMetShouldFlush(a,b)};RichMediaCreativeDisplayManager_60_10.prototype.getShouldFlush=function(a){var b=this.getEventBin();return b&&b.getShouldFlush(a)};
RichMediaCreativeDisplayManager_60_10.prototype.registerUrl=function(a,b){var c=this.getEventBin();if(c)c.registerEventBinUrl(a,b)};RichMediaCreativeDisplayManager_60_10.prototype.logExitEventFlushCounters=function(a,b,c,d){this.logEvent("Exit",a,b,c,d);this.flushCounters(b)};RichMediaCreativeDisplayManager_60_10.prototype.logEventFlushCounters=function(a,b,c,d,e){this.logExitEventFlushCounters(b,c,d,e)};
RichMediaCreativeDisplayManager_60_10.prototype._logEventFlushCountersOpenPopup=function(a,b,c,d,e,f,g){this.logEvent(a,b,c,true);this.flushCounters(c);this.openPopup(d,e,f,g)};RichMediaCreativeDisplayManager_60_10.prototype.getExitUrl=function(a,b){var c=b==undefined?this.creative.exitEvents[a].url:b;var d=this.creative.clickThroughUrl;var e=this.creative.clickN!=""?parseInt(this.creative.clickN):1;if(d.indexOf("?")>=0||d.indexOf("&")>=0)for(var f=0;f<e;f++)c=escape(c);return d+c};
RichMediaCreativeDisplayManager_60_10.prototype.logInteractiveImpression=function(){if(!this.interactiveImpressionLogged){this.logEvent("Count",this.STANDARD_EVENT_INTERACTIVE_IMPRESSION);this.interactiveImpressionLogged=true}};
RichMediaCreativeDisplayManager_60_10.prototype.logExitFlushEventsOpenPopup=function(a,b,c,d,e,f){var g=this.creative.exitEvents[b];var h=this.getExitUrl(b);e=e=="null"?null:e;f=(f="null")?null:f;if(e)h=this.getExitUrl(b,f);else if(f!=null&&f!=""){h=h.indexOf("?")!=-1&&f.charAt(0)!="&"&&h.charAt(h.length-1)!="?"?h+"&":h;h=h.indexOf("?")==-1&&f.indexOf("?")==-1?h+"?":h;h+=f}this.logInteractiveImpression();this.logExitEventFlushCounters(b,c,true,true);if(g.customizedWindow)this.openPopup(h,"motifWindow",
g.windowFeatures,false);else this.openPopup(h,"motifWindow",null,false)};RichMediaCreativeDisplayManager_60_10.prototype.setExpandingManager=function(a){this.expandingManager=a};RichMediaCreativeDisplayManager_60_10.prototype.hasExpandingManager=function(){return typeof this.expandingManager!="undefined"};RichMediaCreativeDisplayManager_60_10.prototype.setFloatingManager=function(a){this.floatingManager=a};
RichMediaCreativeDisplayManager_60_10.prototype.hasFloatingManager=function(){return typeof this.floatingManager!="undefined"};RichMediaCreativeDisplayManager_60_10.prototype.expandAsset=function(a){if(this.creative.shouldDisplayHTML5Asset)this.expandHTMLAsset(a);else this.expandFlashAsset(a)};
RichMediaCreativeDisplayManager_60_10.prototype.expandHTMLAsset=function(a){var b=this.getAsset(a);var c=b.expandedWidth!=undefined?b.expandedWidth:b.width;var d=b.expandedHeight!=undefined?b.expandedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;if(e)this._adjustWindowElements(a,true);if(e&&b.pushContents)this.expandingManager.startAnimation(b,true,true);else this.unclipFlashObject(b,c,d,true)};
RichMediaCreativeDisplayManager_60_10.prototype.expandFlashAsset=function(a){var b=this.getAsset(a);var c=b.expandedWidth!=undefined?b.expandedWidth:b.width;var d=b.expandedHeight!=undefined?b.expandedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;var f=this.toObject("FLASH_"+a);var g=this.hasExpandingManager()&&this.expandingManager.isMultiDirectionalExpanding(f);if(e&&!this.isInAdSenseIFrame()&&g)var h=this.expandingManager.getExpandingDirection(b);if(this.adListener)this.adListener.expand();
if(e)this._adjustWindowElements(a,true);if(e&&b.pushContents)this.expandingManager.startAnimation(b,true,false);else this.unclipFlashObject(b,c,d,false);if(e&&g)if(this.isInAdSenseIFrame())this.expandingManager.creativeToolset.expandWindow();else this.multiDirectionExpand(f,h)};RichMediaCreativeDisplayManager_60_10.prototype.multiDirectionExpand=function(a,b){try{this.setFlashVariable(this.creative.asVersion,a,"mde_expandedDirection",b)}catch(c){}};
RichMediaCreativeDisplayManager_60_10.prototype.collapseAsset=function(a){if(this.creative.shouldDisplayHTML5Asset)this.collapseHTMLAsset(a);else this.collapseFlashAsset(a)};
RichMediaCreativeDisplayManager_60_10.prototype.collapseHTMLAsset=function(a){var b=this.getAsset(a);var c=b.collapsedWidth!=undefined?b.collapsedWidth:b.width;var d=b.collapsedHeight!=undefined?b.collapsedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;if(e&&b.pushContents)this.expandingManager.startAnimation(b,false,true);else this.clipFlashObject(b,c,d,b.offsetTop,b.offsetRight,b.offsetBottom,b.offsetLeft,true);if(e)this._adjustWindowElements(a,false)};
RichMediaCreativeDisplayManager_60_10.prototype.collapseFlashAsset=function(a){var b=this.getAsset(a);var c=b.collapsedWidth!=undefined?b.collapsedWidth:b.width;var d=b.collapsedHeight!=undefined?b.collapsedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;if(e&&b.pushContents)this.expandingManager.startAnimation(b,false,false);else this.clipFlashObject(b,c,d,b.offsetTop,b.offsetRight,b.offsetBottom,b.offsetLeft,false);if(e)this._adjustWindowElements(a,false);var f=this.toObject("FLASH_"+
a);var g=this.hasExpandingManager()&&this.expandingManager.isMultiDirectionalExpanding(f);if(e&&g)if(this.isInAdSenseIFrame())this.expandingManager.creativeToolset.collapseWindow();else this.multiDirectionCollapse(f);if(this.adListener)this.adListener.collapse()};RichMediaCreativeDisplayManager_60_10.prototype.multiDirectionCollapse=function(a){try{this.setFlashVariable(this.creative.asVersion,a,"mde_expandedState","collapsed")}catch(b){}};
RichMediaCreativeDisplayManager_60_10.prototype.onMouseOver=function(a){try{var b=this.toObject("FLASH_"+a);this.setFlashVariable(this.creative.asVersion,b,"isMouseOver","1")}catch(c){}};RichMediaCreativeDisplayManager_60_10.prototype.onMouseOut=function(a){try{var b=this.toObject("FLASH_"+a);this.setFlashVariable(this.creative.asVersion,b,"isMouseOver","0")}catch(c){}};
RichMediaCreativeDisplayManager_60_10.prototype.onMouseOverHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","1"],a)}catch(b){}};RichMediaCreativeDisplayManager_60_10.prototype.onMouseOutHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","0"],a)}catch(b){}};RichMediaCreativeDisplayManager_60_10.prototype.onTouchHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","1"],a)}catch(b){}};
RichMediaCreativeDisplayManager_60_10.prototype.onTouchEndHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","0"],a)}catch(b){}};RichMediaCreativeDisplayManager_60_10.prototype.scheduleCallbackOnLoad=function(a){a='dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+a;this.registerPageLoadHandler(a,null)};
RichMediaCreativeDisplayManager_60_10.prototype.scheduleDisplay=function(a,b,c){b=this._convertDuration(b);if(c)this._adjustWindowElements(a,true);if(b=="AUTO")this.registerTimeoutHandler(1000,"_autoStopPlaying('"+a+"')",this);else if(b>0)this.registerTimeoutHandler(eval(b)*1000,"stopDisplay('"+a+"')",this)};RichMediaCreativeDisplayManager_60_10.prototype.tellCompanionAssetStop=function(a){this.dualAssetManager.tellCompanionAssetStop(a)};
RichMediaCreativeDisplayManager_60_10.prototype.tellCompanionAssetStart=function(a){this.dualAssetManager.tellCompanionAssetStart(a)};RichMediaCreativeDisplayManager_60_10.prototype.tellCompanionAssetHide=function(a){this.dualAssetManager.tellCompanionAssetHide(a)};RichMediaCreativeDisplayManager_60_10.prototype.tellCompanionAssetShow=function(a){this.dualAssetManager.tellCompanionAssetShow(a)};
RichMediaCreativeDisplayManager_60_10.prototype.getAsset=function(a){if(this.creative.assets["floatAssets"])for(var b=0;b<this.creative.assets["floatAssets"].length;b++){var c=this.creative.assets["floatAssets"][b];if(c.variableName==a)return c}else for(var d in this.creative.assets)if(!this.isPartOfArrayPrototype(d)&&this.creative.assets[d].variableName==a)return this.creative.assets[d];return null};
RichMediaCreativeDisplayManager_60_10.prototype.getHTML5Asset=function(){for(var a in this.creative.assets)if(!this.isPartOfArrayPrototype(a))return this.creative.assets[a];return null};RichMediaCreativeDisplayManager_60_10.prototype.tellAssetHide=function(a){var b=this.getAssetType(a);if(b==this.ASSET_TYPE_OVERLAY)this.closePopupAsset(a);else this.stopDisplay(a)};RichMediaCreativeDisplayManager_60_10.prototype.tellAssetShow=function(a){this._startDisplay(a,false)};
RichMediaCreativeDisplayManager_60_10.prototype.tellAssetStart=function(a){if(this.isFlashScriptingSupported())this.playFlash(a)};RichMediaCreativeDisplayManager_60_10.prototype.tellAssetStop=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())b.StopPlay()};RichMediaCreativeDisplayManager_60_10.prototype.tellAssetGotoFrame=function(a,b){var c=this.toObject("FLASH_"+a);if(c&&this.isFlashScriptingSupported())c.GotoFrame(b)};
RichMediaCreativeDisplayManager_60_10.prototype.isAssetPlaying=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())return b.IsPlaying();return false};
RichMediaCreativeDisplayManager_60_10.prototype.replayAsset=function(a){var b=this.toObject("DIV_"+a);if(b&&b.style.visibility!="visible"){b.style.visibility="visible";var c=this.getAsset(a);if(c!=null){var d=this.toObject("FLASH_"+a);d.Rewind();d.StopPlay();this.scheduleDisplay(a,c.duration,true);if(c.isMainAsset){var e=this.getRenderingId(a);this.logEvent("Start","DISPLAY_TIMER",e)}}}};
RichMediaCreativeDisplayManager_60_10.prototype.openPopup=function(a,b,c,d){if(c)var e=window.open(a,b,c);else e=window.open(a,b);this.dartPopupArray[b]=e;if(eval(d))window.focus();return e};
RichMediaCreativeDisplayManager_60_10.prototype.notifyPreviewHandler=function(a,b){if(this.creative.debugEventsMode&&this.previewHandler)try{if(b=="startDisplay"){var c=this.generateGlobalCallback("replayAsset('"+a.variableName+"')",this);this.previewHandler.onAssetDisplayed("DIV_"+a.variableName,a.assetType,c)}else if(b=="stopDisplay")this.previewHandler.onBeforeAssetRemoved("DIV_"+a.variableName,a.assetType)}catch(d){}};
RichMediaCreativeDisplayManager_60_10.prototype.stopDisplay=function(a){var b=this.toObject("DIV_"+a);if(b.style.visibility=="hidden")return;var c=this.getAsset(a);this.notifyPreviewHandler(c,"stopDisplay");var d=this.toObject("FLASH_"+a);if(!d)d=this.toObject("IFRAME_"+a);var e=this.creative.renderingId;if(c.isMainAsset)this.stopStandardTimers(e);this.flushCounters(e);if(!this.isAnyCompanionVisible(a))this.scheduleTurnOffEventBinFlushing(e,2);b.removeChild(d);b.style.visibility="hidden";this._adjustWindowElements(a,
false)};RichMediaCreativeDisplayManager_60_10.prototype.isAnyCompanionVisible=function(a){for(var b in this.assets)if(!this.isPartOfArrayPrototype(b)&&b!=a){var c=this.toObject("DIV_"+b);if(c&&c.style.visibility=="visible")return true}return false};RichMediaCreativeDisplayManager_60_10.prototype.addEntityProperties=function(a,b,c,d,e,f,g){this.pageElementsManager.addEntityProperties(a,b,c,d,e,f,g)};
RichMediaCreativeDisplayManager_60_10.prototype.doNotAdjustIFrame=function(a,b){this.pageElementsManager.doNotAdjustIFrame(a,b)};RichMediaCreativeDisplayManager_60_10.prototype.doNotAdjustObject=function(a,b){this.pageElementsManager.doNotAdjustObject(a,b)};RichMediaCreativeDisplayManager_60_10.prototype.getRenderingId=function(a){var b=a.split("_");return b.length>1?b[0]:null};
RichMediaCreativeDisplayManager_60_10.prototype.createFunctionCall=function(a,b){var c=a+"(";var d=0;for(var e=0;e<b.length;e++){if(d>0)c+=", ";c+='"'+b[e]+'"';d++}c+=")";return c};RichMediaCreativeDisplayManager_60_10.prototype._splitArgs=function(a){var b=new Array;var c=unescape(a);var d=c.split("#mtf#");for(var e=0;e<d.length;e++)b[e]=d[e];return b};
RichMediaCreativeDisplayManager_60_10.prototype._parseCommandString=function(a){var b=new Object;b.command=unescape(a.split("=")[0]);b.argString=unescape(a.split("=")[1]);var c=b.argString.split("#mtf#");b.argArray=new Array;for(var d=0;d<c.length;d++)b.argArray[d]=c[d]=="null"?null:c[d];return b};
RichMediaCreativeDisplayManager_60_10.prototype._startDisplay=function(a,b){var c=this.toObject("DIV_"+a);var d=this.toObject("FLASH_"+a);if(b)this._adjustWindowElements(a,true);if(c)c.style.visibility="visible";if(d&&this.isFlashScriptingSupported())this.playFlash(a);var e=this.creative.renderingId;if(d&&this.debugEventsMode){if(!this.dartDebugEventBin.getShouldFlush(e)){this.setShouldFlush(e,true);this.dartDebugEventBin.flushMetCounters(e)}}else if(d&&!this.previewMode&&!this.dartEventBin.getShouldFlush(e))this.setShouldFlush(e,
true)};RichMediaCreativeDisplayManager_60_10.prototype.playFlash=function(a){var b=this.toObject("FLASH_"+a);var c=this.getAsset(a);var d=c.assetType;if(this.isInternetExplorer())b.Play();else if(d=="float"||d=="reminder"||d=="banner"||d=="expando")if(c.conduitInitialized){if(b.TCurrentFrame("/")<=0)b.Play()}else this.registerTimeoutHandler(100,"playFlash('"+a+"')",this)};
RichMediaCreativeDisplayManager_60_10.prototype._autoStopPlaying=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())if(b.PercentLoaded()==100&&!b.IsPlaying())this.stopDisplay(a);else this.registerTimeoutHandler(300,"_autoStopPlaying('"+a+"')",this)};RichMediaCreativeDisplayManager_60_10.prototype._adjustWindowElements=function(a,b){this.pageElementsManager._adjustWindowElements(a,b)};RichMediaCreativeDisplayManager_60_10.prototype.triggerPoliteDownload=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a))this.finishPoliteDownload(a)};
RichMediaCreativeDisplayManager_60_10.prototype.finishPoliteDownload=function(a){var b=this.toObject("FLASH_"+a);if(this.isFlashObjectReady(this.creative.asVersion,b,a))this.setFlashVariable(this.creative.asVersion,b,"mtfContinue","1");else{var c="dartCreativeDisplayManagers['"+this.creativeIdentifier+"'].finishPoliteDownload('"+a+"');";window.setTimeout(c,100)}};RichMediaCreativeDisplayManager_60_10.prototype.triggerDispatchScriptLoaded=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a))this.finishDispatchScriptLoaded(a)};
RichMediaCreativeDisplayManager_60_10.prototype.finishDispatchScriptLoaded=function(a){var b=this.toObject("FLASH_"+a);try{if(b&&typeof b.PercentLoaded!="undefined"&&b.PercentLoaded()>0&&typeof b.TCurrentFrame!="undefined"&&b.TCurrentFrame("/")>=0)this.setFlashVariable(this.creative.asVersion,b,"globalTemplateScriptLoaded","1");else{var c="dartCreativeDisplayManagers['"+this.creativeIdentifier+"'].finishDispatchScriptLoaded('"+a+"');";window.setTimeout(c,100)}}catch(d){c="dartCreativeDisplayManagers['"+
this.creativeIdentifier+"'].finishDispatchScriptLoaded('"+a+"');";window.setTimeout(c,100)}};RichMediaCreativeDisplayManager_60_10.prototype.unloadPopup=function(){var a=this.renderingId;if(a){this.flushCounters(a);this.stopStandardTimers(a)}};RichMediaCreativeDisplayManager_60_10.prototype.forceAnimation=function(a){var b=this.toObject("FLASH_"+a);var c=this.toObject("DIV_"+a);if(c.style.visibility=="visible"){b.Zoom(50);b.Zoom(0)}};
RichMediaCreativeDisplayManager_60_10.prototype.isFlashScriptingSupported=function(){return this.isWindows()||this.isMac()&&(this.isFirefox()||this.isSafari()||this.isChrome())};RichMediaCreativeDisplayManager_60_10.prototype.registerCreativeElement=function(a){this.rootElementArray[this.rootElementArray.length]=a};
RichMediaCreativeDisplayManager_60_10.prototype.removeChildNode=function(a,b){if(a.hasChildNodes()){var c=a.childNodes;for(var d=0;d<c.length;d++)this.removeChildNode(c[d],b)}else{var e=a.parentNode;e.removeChild(a);if(b!=e)this.removeChildNode(e,b)}};RichMediaCreativeDisplayManager_60_10.prototype.openPopupAsset=function(){if(this.overlay)this.overlay._openPopup()};RichMediaCreativeDisplayManager_60_10.prototype.closePopupAsset=function(){if(this.overlay)this.overlay._closePopup()};
RichMediaCreativeDisplayManager_60_10.prototype.registerOverlay=function(a){this.overlay=a};RichMediaCreativeDisplayManager_60_10.prototype.getAssetType=function(a){for(var b in this.creative.assets)if(this.creative.assets[b].variableName==a)return b;return null};RichMediaCreativeDisplayManager_60_10.prototype.setServedInIframe=function(a){this.servedInIframe=a};RichMediaCreativeDisplayManager_60_10.prototype.isServedInIframe=function(){return this.sourceIframe!=null};
RichMediaCreativeDisplayManager_60_10.prototype.setSourceIframe=function(a){this.sourceIframe=a};RichMediaCreativeDisplayManager_60_10.prototype.getSourceIframe=function(){return this.sourceIframe};RichMediaCreativeDisplayManager_60_10.prototype.createHTML5AdIframe=function(a){var b="IFRAME_"+a.variableName;var c=document.createElement("IFRAME");c.id=b;c.src=a.url;c.scrolling="no";c.frameBorder="0";c.seamless=true;c.width=a.width;c.height=a.height;return c};
RichMediaCreativeDisplayManager_60_10.prototype.invokeExternalJSFunction=function(a){if(this.creative.type!=this.CREATIVE_TYPE_EXPANDING)return;if(this.previewMode){var b=this.getEventBin();if(b!=null)b.logExternalJSFunctionCall(unescape(a),this.creative.renderingId)}else try{eval(unescape(a))}catch(c){}};RichMediaCreativeDisplayManager_60_10.prototype.setThrottlingWindow=function(a){var b=this.getEventBin();if(b!=null)if(this._isValidNumber(a))b.setMinimumFlushingDuration(parseFloat(a))};
RichMediaCreativeDisplayManager_60_10.prototype.logHTML5Impression=function(){var a=this.getEventBin();if(a){var b=this.getStandardEventId(this.STANDARD_EVENT_HTML5_CREATIVE_IMPRESSION);a.logMetEvent("Count",b,this.creative.renderingId,false,this.STANDARD_EVENT_HTML5_CREATIVE_IMPRESSION)}};RichMediaCreativeDisplayManager_60_10.prototype.attachMessageHandler=function(){self.addEventListener("message",this.bind(this,this.messageHandler),false)};
RichMediaCreativeDisplayManager_60_10.prototype.bind=function(a,b){var c=arguments.length>2?arguments.slice(2):[];return function(){return b.apply(a,arguments.slice?arguments.concat(c):arguments)}};RichMediaCreativeDisplayManager_60_10.prototype.messageHandler=function(a){var b=this.toObject(this.html5IframeId);if(b.contentWindow==a.source)this.messageCommandHandler(a)};
RichMediaCreativeDisplayManager_60_10.prototype.messageCommandHandler=function(a){var b=a.data;var c=this._parseCommandString(unescape(b));var d=this.createFunctionCall(c.command,c.argArray);try{eval('dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+d)}catch(e){}};
RichMediaCreativeDisplayManager_60_10.prototype.invokeEnablerFunction=function(a,b,c){var d={};d.methodName=a;if(b&&b.join&&b.length>0)b=b.join("#mtf#");d.args=b?b:null;var e=this.getAsset(c);var f=document.getElementById("IFRAME_"+c).contentWindow;var g=this.getSiteProtocol(e.url)+"//"+this.getSiteHost(e.url);if(f)f.postMessage(escape(this.serializeCommand(d)),g)};RichMediaCreativeDisplayManager_60_10.prototype.serializeCommand=function(a){return escape(a.methodName)+"="+escape(a.args)};
RichMediaCreativeDisplayManager_60_10.prototype.setAdParameters=function(){var a=this.getHTML5Asset();if(a!=null)this.invokeEnablerFunction("setAdParameters",a.queryString,a.variableName)};
function RichMediaEventBin_60_10(a,b,c){this.dartIntervalArray=b?new Array:new Array(10,20,50,120,240);this.dartEventBinCollection=new Array;this.dartRegistrationTime=null;this.dartMaxTimeMilliseconds=20*60*1000;this.dartCreativeIdentifier=a;this.timerAdjustments=new Array;this.lastEventFlushingTime=null;this.minimumFlushingDuration=5*1000;this.importantEventsArray=c;this.dynamicServeId=null}RichMediaEventBin_60_10.prototype=new RichMediaCore_60_10;
RichMediaEventBin_60_10.prototype.setTimerAdjustment=function(a,b,c){var d=new Object;d.eventId=a;d.startAdjustmentTime=parseInt(b);d.stopAdjustmentTime=parseInt(c);this.timerAdjustments[a]=d};
RichMediaEventBin_60_10.prototype.registerEventBinUrl=function(a,b){if(!this.dartEventBinCollection[a]){var c=new Array;c["counter"]=new Array;c["timer"]=new Array;c["duration"]=new Array;c["nonCumulativeCounters"]=new Array;c["flushUrl"]=b;c["shouldFlush"]=true;this.dartEventBinCollection[a]=c;this.dartRegistrationTime=new Date;this.setFlushInterval(a)}};RichMediaEventBin_60_10.prototype.setDynamicServeId=function(a){this.dynamicServeId=a};
RichMediaEventBin_60_10.prototype.logMetEvent=function(a,b,c,d){if(this.dartEventBinCollection[c]&&b&&!isNaN(b))switch(a){case "Count":{this.processCounter(b,c,d);break}case "Start":{this.processStart(b,c);break}case "Stop":{this.processStopTimer(b,c);break}default:break}};
RichMediaEventBin_60_10.prototype.processCounter=function(a,b,c){var d=this.getNonCumulativeCountersArray(b);var e=this.getCounterArray(b);c=c&&(c=="true"||c==true);if(!c){if(!d[a])e[a]=1;d[a]=true}else{if(!e[a])e[a]=0;e[a]=e[a]+1}};RichMediaEventBin_60_10.prototype.processStart=function(a,b){var c=this.getTimerArray(b);if(!c[a]){var d=new Date;var e=this.timerAdjustments[a];if(e){var f=d.getTime()+e.startAdjustmentTime;d.setTime(f)}c[a]=d;this.processCounter(a,b,false)}};
RichMediaEventBin_60_10.prototype.processStopTimer=function(a,b){var c=this.getTimerArray(b);var d=this.getDurationArray(b);if(c[a]){var e=c[a];var f=new Date;var g=f.getTime()-e.getTime();if(g<0||g>this.dartMaxTimeMilliseconds)g=0;d[a]=d[a]?d[a]+g:g;c[a]=false;return true}return false};RichMediaEventBin_60_10.prototype.shouldFlush=function(){var a=(new Date).getTime();return this.lastEventFlushingTime==null?true:a-this.lastEventFlushingTime>this.minimumFlushingDuration};
RichMediaEventBin_60_10.prototype.hasAnyImportantEventPending=function(a){var b=this.getCounterArray(a);for(var c in b)if(!this.isPartOfArrayPrototype(c)&&b[c]>0)for(var d=0;d<this.importantEventsArray.length;d++)if(c==this.importantEventsArray[d])return true;return false};
RichMediaEventBin_60_10.prototype.flushMetCounters=function(a){if(this.dartEventBinCollection[a]&&this.getShouldFlush(a)){var b="";var c=this.getCounterArray(a);var d=this.getDurationArray(a);var e=this.getTimerArray(a);var f=1;if((this.shouldFlush()||this.hasAnyImportantEventPending(a))&&this.isInAllowedTimeframe()){for(var g in c)if(!this.isPartOfArrayPrototype(g)){var h=this.processStopTimer(g,a);var i=c[g];if(!d[g])d[g]=0;var j=this.roundNumber(d[g]?parseFloat(String(d[g]/1000)):0);if(i>0||j>
0){b+="eid"+f+"="+g+";";b+="ecn"+f+"="+i+";";b+="etm"+f+"="+j+";"}c[g]=c[g]-i;d[g]=d[g]-j*1000;if(h)e[g]=new Date;f++}this.lastEventFlushingTime=(new Date).getTime();this.postData(b,a)}}};RichMediaEventBin_60_10.prototype.turnOffFlushing=function(a){this.flushMetCounters(a);this.setMetShouldFlush(false)};
RichMediaEventBin_60_10.prototype.postData=function(a,b){if(a.length){var c=new Date;var d=this.splitActivity(a);for(var e=0;e<d.length;e++){var f=document.createElement("img");var g=d[e];f.src=this.getFlushUrl(b)+this.getDynamicServeKeyvalue()+"&timestamp="+c.getTime()+";"+g}}};RichMediaEventBin_60_10.prototype.getDynamicServeKeyvalue=function(){return this.dynamicServeId?"rm_mid="+escape(this.dynamicServeId)+";":""};
RichMediaEventBin_60_10.prototype.splitActivity=function splitActivity(b){var c=new Array;var d="etm";var e=950;for(var f=0;b.length>0;b=b.substr(f)){var g=b;var h=g.substr(0,e);f=h.lastIndexOf(d)+d.length;h=g.substr(0,f);g=g.substr(f);f+=g.indexOf(";")+1;c[c.length]=b.substr(0,f)}return c};RichMediaEventBin_60_10.prototype.getCounterArray=function(a){var b=this.dartEventBinCollection[a];return b["counter"]};
RichMediaEventBin_60_10.prototype.getTimerArray=function(a){var b=this.dartEventBinCollection[a];return b["timer"]};RichMediaEventBin_60_10.prototype.getDurationArray=function(a){var b=this.dartEventBinCollection[a];return b["duration"]};RichMediaEventBin_60_10.prototype.getNonCumulativeCountersArray=function(a){var b=this.dartEventBinCollection[a];return b["nonCumulativeCounters"]};RichMediaEventBin_60_10.prototype.getFlushUrl=function(a){var b=this.dartEventBinCollection[a];return b["flushUrl"]};
RichMediaEventBin_60_10.prototype.getShouldFlush=function(a){var b=this.dartEventBinCollection[a];return b["shouldFlush"]};RichMediaEventBin_60_10.prototype.setMetShouldFlush=function(a,b){var c=this.dartEventBinCollection[a];if(c)c["shouldFlush"]=b};RichMediaEventBin_60_10.prototype.isInAllowedTimeframe=function(){var a=new Date;return!(a.getTime()-this.dartRegistrationTime.getTime()>this.dartMaxTimeMilliseconds)};
RichMediaEventBin_60_10.prototype.roundNumber=function(a,b){b=b?b:0;return Math.round(a*Math.pow(10,b))/Math.pow(10,b)};RichMediaEventBin_60_10.prototype.setFlushInterval=function(a){for(var b=0;b<this.dartIntervalArray.length;b++){var c=this.dartIntervalArray[b]*1000;this.registerTimeoutHandler(c,"flushMetCounters('"+a+"')",this)}};RichMediaEventBin_60_10.prototype.setMinimumFlushingDuration=function(a){this.minimumFlushingDuration=a*1000};
function MSNAdListener_60_10(a){this.asset=a;this.init()}MSNAdListener_60_10.prototype=new RichMediaCore_60_10;MSNAdListener_60_10.prototype.init=function(){var a=this.getAssetOffset();try{$WLXRmAd.init({width:parseFloat(this.asset.width),height:parseFloat(this.asset.height),offsetLeft:a.offsetLeft,offsetRight:a.offsetRight,offsetTop:a.assetTop,offsetBottom:a.offsetBottom})}catch(b){}};
MSNAdListener_60_10.prototype.getAssetOffset=function(){var a=new Object;a.offsetLeft=parseFloat(this.asset.offsetLeft)==0?0:parseFloat(this.asset.offsetLeft);a.offsetRight=parseFloat(this.asset.expandedWidth)==parseFloat(this.asset.offsetRight)?0:parseFloat(this.asset.expandedWidth)-parseFloat(this.asset.offsetRight);a.offsetTop=parseFloat(this.asset.offsetTop)==0?0:parseFloat(this.asset.offsetTop);a.offsetBottom=parseFloat(this.asset.expandedHeight)==parseFloat(this.asset.offsetBottom)?0:parseFloat(this.asset.expandedHeight)-
parseFloat(this.asset.offsetBottom);return a};MSNAdListener_60_10.prototype.expand=function(){try{$WLXRmAd.expand()}catch(a){}};MSNAdListener_60_10.prototype.collapse=function(){try{$WLXRmAd.collapse()}catch(a){}};function YahooAdListener_60_10(a){this.asset=a;this.init()}YahooAdListener_60_10.prototype=new RichMediaCore_60_10;YahooAdListener_60_10.prototype.init=function(){try{Y.SandBox.vendor.register(parseFloat(this.asset.width),parseFloat(this.asset.height))}catch(a){}};
YahooAdListener_60_10.prototype.getAssetOffset=function(){var a=new Object;a.offsetX=parseFloat(this.asset.offsetLeft)==0?parseFloat(this.asset.expandedWidth)-parseFloat(this.asset.width):-(parseFloat(this.asset.expandedWidth)-parseFloat(this.asset.width));a.offsetY=parseFloat(this.asset.offsetTop)==0?parseFloat(this.asset.expandedHeight)-parseFloat(this.asset.height):-(parseFloat(this.asset.expandedHeight)-parseFloat(this.asset.height));return a};
YahooAdListener_60_10.prototype.expand=function(){var a=this.getAssetOffset();try{Y.SandBox.vendor.expand(a.offsetX,a.offsetY)}catch(b){}};YahooAdListener_60_10.prototype.collapse=function(){try{Y.SandBox.vendor.collapse()}catch(a){}};function PageElementsManager_60_10(a,b){this.creative=a;this.displayManager=b;this.dartEntityPropertiesArray=new Object;this.noAdjustElements=new _doNotAdjustElement;this.iframePlaceHolderDivIndex=0;this.hiddenIframes=new Array}PageElementsManager_60_10.prototype=new RichMediaCore_60_10;
PageElementsManager_60_10.prototype.addEntityProperties=function(a,b,c,d,e,f,g){this.dartEntityPropertiesArray[a]=new _entityProperties(b,c,d,e,f,g)};PageElementsManager_60_10.prototype.doNotAdjustIFrame=function(a,b){this.noAdjustElements.iFrames[this.noAdjustElements.iFrames.length]=b};PageElementsManager_60_10.prototype.doNotAdjustObject=function(a,b){this.noAdjustElements.objects[this.noAdjustElements.objects.length]=b};
PageElementsManager_60_10.prototype._adjustWindowElements=function(a,b){var c=this.dartEntityPropertiesArray[a];if(c){if(c.hideDropDowns)this._adjustElements(b,"select");if(c.hideScrollBars&&(this.isInternetExplorer()||this.isSafari()))this.adjustScrollbars(b);if(c.hideIFrames)this._adjustElements(b,"iframe");if(c.hideObjects){this._adjustElements(b,"object");this._adjustElements(b,"embed")}if(c.hideApplets)this._adjustElements(b,"applet");if(c.adjustZIndex)this._adjustZIndex(a,b)}};
PageElementsManager_60_10.prototype._adjustZIndex=function(a,b){try{this._adjustParentZIndex(a,b)}catch(c){}};
PageElementsManager_60_10.prototype._adjustParentZIndex=function(a,b){var c=this.toObject("DIV_"+a);var d=null;var e=this.displayManager.getAsset(a);if(c&&typeof e.assetType!="undefined"&&e.assetType==this.ASSET_TYPE_EXPANDING)d=c.parentNode.parentNode;else return;for(;d&&d.tagName!="BODY";){if(b){var f=this.getStyle(d);if(c.style.zIndex>f.zIndex&&(f.position=="relative"||f.position=="absolute")){d.style.originalZIndex=this.getStyle(d).zIndex;d.style.zIndex=c.style.zIndex}}else if(typeof d.style.originalZIndex!=
"undefined")d.style.zIndex=d.style.originalZIndex;d=d.parentNode}};PageElementsManager_60_10.prototype._adjustElements=function(a,b){var c=self.document.getElementsByTagName(b);b=b.toLowerCase();for(var d=0;d<c.length;d++){var e=true;if(b=="iframe")if(typeof c[d].MotifIFrameIDArray!="undefined")e=this._shouldAdjustIFrame(c[d].MotifIFrameIDArray);else e=!this.isHTML5ContainerIframe(c[d].id);else if(b=="object"||b=="embed")e=!this.isMotifObject(c[d].id);if(e)a?this.hideElement(c[d]):this.showElement(c[d])}};
PageElementsManager_60_10.prototype.hideElement=function(a){var b=a.getAttribute("hideCount");if(b==null||b==""){a.setAttribute("initialVisibility",a.style.visibility);a.setAttribute("hideCount",0)}var c=parseInt(a.getAttribute("hideCount"));if(c==0)if(a.tagName.toLowerCase()=="iframe"&&this.isFirefox())this.hideFirefoxIFrame(a);else a.style.visibility="hidden";c++;a.setAttribute("hideCount",c)};
PageElementsManager_60_10.prototype.showElement=function(a){if(a.getAttribute("hideCount")!=null){var b=parseInt(a.getAttribute("hideCount"));if(b!=0)b--;a.setAttribute("hideCount",b);if(b==0)if(a.tagName.toLowerCase()=="iframe"&&this.isFirefox())this.displayFirefoxIFrame(a);else a.style.visibility=a.getAttribute("initialVisibility")}};
PageElementsManager_60_10.prototype._shouldAdjustIFrame=function(a){var b=this.noAdjustElements.iFrames;for(var c=0;c<b.length;c++)for(var d=0;d<a.length;d++)if(b[c]==a[d])return false;return true};
PageElementsManager_60_10.prototype.isMotifObject=function(a){for(var b=0;b<dartMotifAds.length;b++){var c=dartMotifAds[b];if(c.assets["floatAssets"])for(b=0;b<c.assets["floatAssets"].length;b++){var d=c.assets["floatAssets"][b];if(a=="FLASH_"+d.variableName)return true}else for(var e in c.assets)if(a=="FLASH_"+c.assets[e].variableName)return true}return false};
PageElementsManager_60_10.prototype.isHTML5ContainerIframe=function(a){for(var b=0;b<dartMotifAds.length;b++){var c=dartMotifAds[b];for(var d in c.assets)if(a=="IFRAME_"+c.assets[d].variableName)return true}return false};function _entityProperties(a,b,c,d,e,f){this.hideDropDowns=a;this.hideIFrames=b;this.hideScrollBars=c;this.hideObjects=d;this.hideApplets=e;this.adjustZIndex=f}function _doNotAdjustElement(){this.iFrames=new Array;this.objects=new Array}
PageElementsManager_60_10.prototype.hideFirefoxIFrame=function(a){var b=null;var c=null;if(!a.hasAttribute("Motif_IFramePlaceHolderDivIndex")){b=document.createElement("DIV");b.id="MOTIF_IFRAMEPLACEHOLDER_"+this.iframePlaceHolderDivIndex;b.style.width="0px";b.style.height="0px";b.style.visibility="hidden";b.style.padding="0px";b.style.margin="0px";b.style.display="inline";a.parentNode.insertBefore(b,a);b.innerHTML='<img src="" width="0px" height="0px" padding="0px" margin="0px"></img>';a.setAttribute("Motif_IFramePlaceHolderDivIndex",
this.iframePlaceHolderDivIndex);c=new Object;this.hiddenIframes[this.iframePlaceHolderDivIndex]=c;this.iframePlaceHolderDivIndex++}else{var d=a.getAttribute("Motif_IFramePlaceHolderDivIndex");var e="MOTIF_IFRAMEPLACEHOLDER_"+d;b=document.getElementById(e);c=this.hiddenIframes[parseInt(d)]}c.width=a.width;c.height=a.height;b.style.width=c.width;b.style.height=c.height;b.firstChild.width=c.width;b.firstChild.height=c.height;a.style.visibility="hidden";a.width=0;a.height=0};
PageElementsManager_60_10.prototype.displayFirefoxIFrame=function(a){var b=a.getAttribute("Motif_IFramePlaceHolderDivIndex");var c="MOTIF_IFRAMEPLACEHOLDER_"+b;var d=document.getElementById(c);var e=this.hiddenIframes[parseInt(b)];if(d!=null){a.width=e.width;a.height=e.height;d.style.width="0px";d.style.height="0px";d.firstChild.width=0;d.firstChild.height=0}a.style.visibility=a.getAttribute("initialVisibility")};
PageElementsManager_60_10.prototype.adjustScrollbars=function(a){var b=self.document.documentElement;var c=document.compatMode&&document.compatMode=="CSS1Compat";c|=this.isSafari();if(a)if(c){b.style.originalOverflow=typeof b.currentStyle=="object"?b.currentStyle.overflow:b.style.overflow;b.style.overflow="hidden"}else self.document.body.scroll="no";else if(c){if(typeof b.style.originalOverflow!="undefined")b.style.overflow=b.style.originalOverflow}else self.document.body.scroll="yes"};
function ExpandingManager_60_10(a,b){this.creative=a;this.displayManager=b;this.init()}ExpandingManager_60_10.prototype=new RichMediaCore_60_10;
ExpandingManager_60_10.prototype.init=function(){if(this.isInAdSenseIFrame()){this.creativeToolset=new CreativeToolset;var a=this.creative.assets[this.ASSET_TYPE_EXPANDING];var b="dartCallbackObjects["+this.getCallbackObjectIndex(this)+"].adSenseExpand(expandedWidth, expandedHeight, direction)";var c=new Function("expandedWidth","expandedHeight","direction",b);var d="dartCallbackObjects["+this.getCallbackObjectIndex(this)+"].adSenseCollapse(collapsedWidth, collapsedHeight)";var e=new Function("collapsedWidth",
"collapsedHeight",d);var f=parseInt(a.offsetLeft)+parseInt(a.width);var g=parseInt(a.expandedWidth)-parseInt(a.offsetLeft);var h=parseInt(a.offsetTop)+parseInt(a.height);var i=parseInt(a.expandedHeight)-parseInt(a.offsetTop);var j={width:Math.max(f,g),height:Math.max(h,i),expansionCallback:c,collapseCallback:e};this.creativeToolset.enableExpansion(j)}if(this.isInWinLiveAPIPlatform())this.displayManager.adListener=new MSNAdListener_60_10(this.creative.assets[this.ASSET_TYPE_EXPANDING]);else if(this.isInYahooCrossDomainIframe())this.displayManager.adListener=
new YahooAdListener_60_10(this.creative.assets[this.ASSET_TYPE_EXPANDING])};ExpandingManager_60_10.prototype.adSenseExpand=function(a,b,c){try{var d=["tl","tr","br","bl"];var e=this.toObject("FLASH_"+this.creative.assets[this.ASSET_TYPE_EXPANDING].variableName);this.setFlashVariable(this.creative.asVersion,e,"mde_expandedDirection",d[c])}catch(f){}};
ExpandingManager_60_10.prototype.adSenseCollapse=function(a,b){try{var c=this.toObject("FLASH_"+this.creative.assets[this.ASSET_TYPE_EXPANDING].variableName);this.setFlashVariable(this.creative.asVersion,c,"mde_expandedState","collapsed")}catch(d){}};ExpandingManager_60_10.prototype.getPosition=function(a,b){return"position:absolute;"+"top:"+(0-a)+"px;"+"left:"+(0-b)+"px;"};
ExpandingManager_60_10.prototype.startAnimation=function(a,b,c){if(a.animationState==null){var d=new Object;d.isRunning=false;d.animateCallback=this.generateGlobalCallback('updateExpandingViewPort("'+a.variableName+'", '+c+")",this);d.expandMode=true;var e=parseInt(a.height);d.currentHeight=e;var f=parseInt(a.expandedHeight);var g=f-e;var h=a.animationTime*1000;d.updateInterval=50;var i=Math.ceil(h/d.updateInterval);d.stepLength=Math.ceil(g/(i+1));a.animationState=d}a.animationState.expandMode=b;
if(!a.animationState.isRunning){a.animationState.isRunning=true;this.updateExpandingViewPort(a.variableName,c)}};
ExpandingManager_60_10.prototype.updateExpandingViewPort=function(a,b){var c=this.displayManager.getAsset(a);var d=c.animationState;var e=false;var f="auto";var g="auto";var h="auto";if(d.expandMode){var i=parseInt(c.expandedHeight);d.currentHeight+=d.stepLength;if(d.currentHeight>=i){d.currentHeight=i;e=true}}else{var j=parseInt(c.height);f=c.offsetTop;g=c.offsetRight;h=c.offsetLeft;d.currentHeight-=d.stepLength;if(d.currentHeight<=j){d.currentHeight=j;e=true}}var k=this.toObject("EXPANDO_PLACEHOLDER_"+
a);k.style.height=d.currentHeight+"px";var l=f=="auto"?c.expandedWidth:c.width;this.displayManager.clipFlashObject(c,l,d.currentHeight,f,g,d.currentHeight,h,b);if(e)d.isRunning=false;else window.setTimeout(d.animateCallback,d.updateInterval)};
ExpandingManager_60_10.prototype.getExpandingDirection=function(a){var b=this.getElementPosition("OUTER_DIV_"+a.variableName);var c=this.getWindowDimension();var d=this.getAvailableVeticalDirection(c.height,b.top,a.height);var e=this.getAvailableHorizontalDirection(c.width,b.left,a.width);return d+e};ExpandingManager_60_10.prototype.getAvailableVeticalDirection=function(a,b,c){var d=a-(b+parseInt(c));return b>=d?"t":"b"};
ExpandingManager_60_10.prototype.getAvailableHorizontalDirection=function(a,b,c){var d=a-(b+parseInt(c));return b>=d?"l":"r"};ExpandingManager_60_10.prototype.isMultiDirectionalExpanding=function(a){try{return this.getFlashVariable(this.creative.asVersion,a,"isMultiDirectional")=="true"}catch(b){return false}};
ExpandingManager_60_10.prototype.adjustParentOverflow=function(a){for(;a;){if(a.tagName!="BODY"){var b=this.getStyle(a);if(b.overflow=="hidden"||b.overflowX&&b.overflowX=="hidden"||b.overflowY&&b.overflowY=="hidden")a.style.overflow="visible"}if(a.tagName=="BODY")break;a=a.parentNode}};function FlashUtil_60_10(a){this.creative=a}FlashUtil_60_10.prototype=new RichMediaCore_60_10;
FlashUtil_60_10.prototype.getObjectHtml=function(){var a=this.getArgs(arguments);return this.generateObj(a.objAttrs,a.params,a.embedAttrs)};
FlashUtil_60_10.prototype.getArgs=function(a){var b=new Object;b.embedAttrs=new Object;b.params=new Object;b.objAttrs=new Object;var c="";var d=false;for(var e=0;e<a.length;e=e+2){var f=a[e].toLowerCase();switch(f){case "codebase":case "pluginspage":case "type":case "classid":case "minversion":break;case "src":case "movie":b.params["movie"]=b.embedAttrs["src"]=a[e+1];break;case "querystring":c=a[e+1]=a[e+1]+"&br="+escape(this.getBrowser())+"&os="+escape(this.getOS());break;case "width":case "height":case "align":case "vspace":case "hspace":case "class":case "title":case "accesskey":case "name":case "id":case "tabindex":case "alt":case "onmouseover":case "onmouseout":b.embedAttrs[a[e]]=
b.objAttrs[a[e]]=a[e+1];break;case "swliveconnect":b.embedAttrs[a[e]]=a[e+1];break;case "wmode":d=this.isFlashFullScreenSupported(a[e+1]);b.embedAttrs[a[e]]=b.params[a[e]]=a[e+1];break;default:b.embedAttrs[a[e]]=b.params[a[e]]=a[e+1]}}c+="&isFlashFullScreenEnabled="+d;b.params["FlashVars"]=b.embedAttrs["FlashVars"]=c;b.objAttrs["classid"]="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";b.embedAttrs["type"]="application/x-shockwave-flash";b.params["allowScriptAccess"]="always";b.embedAttrs["allowScriptAccess"]=
"always";if(d){b.params["allowFullScreen"]="true";b.embedAttrs["allowFullScreen"]="true"}return b};
FlashUtil_60_10.prototype.generateObj=function(a,b,c){var d="";if(this.isInternetExplorer()){d+="<object ";for(var e in a)if(!this.isPartOfArrayPrototype(e))d+=e+'="'+a[e]+'" ';d+=">";for(e in b)if(!this.isPartOfArrayPrototype(e))d+='<param name="'+e+'" value="'+b[e]+'" /> '}d+="<embed ";for(e in c)if(!this.isPartOfArrayPrototype(e))d+=e+'="'+c[e]+'" ';d+=" ></embed>";if(this.isInternetExplorer())d+="</object>";return d};
FlashUtil_60_10.prototype.getBrowser=function(){if(this.isInternetExplorer())return"ie";else if(this.isFirefox())return"ff";else if(this.isSafari())return"sf";else if(this.isChrome())return"cr";else return"NOT_SUPPORTED"};FlashUtil_60_10.prototype.getOS=function(){if(this.isWindows())return"win";if(this.isMac())return"mac";if(this.isAndroid())return"android";else return"NOT_SUPPORTED"};
FlashUtil_60_10.prototype.isFlashFullScreenSupported=function(a){var b=this.getPluginInfo();var c=this.creative.requiredPlayerVersion;if(c>5&&this.creative.fullScreenEnabled)if(b>=9.115||b>=9.28&&a=="window")return true;return false};function ExpandingIFrameRenderer_60_10(a,b,c){this.flashUtil=new FlashUtil_60_10(c);this.displayManager=a;this.expandingManager=b}ExpandingIFrameRenderer_60_10.prototype=new RichMediaCore_60_10;
ExpandingIFrameRenderer_60_10.prototype.createExpandingDiv=function(a,b,c,d){var e=a.assets[this.ASSET_TYPE_EXPANDING];var f=""+(0-e.offsetTop)+"px";var g=""+(0-e.offsetLeft)+"px";var h=document.createElement("DIV");h.id="DIV_"+e.variableName;h.style.position="absolute";h.style.top=f;h.style.left=g;h.style.visibility="visible";h.style.zIndex=e.zIndex;h.style.textAlign="left";if(e.expandingDivStyleSheet!="")this.applyCSSProperties(h,e.expandingDivStyleSheet);if(!a.shouldDisplayHTML5Asset&&b.usesSalignForExpanding(e.salign,
e.wmode)){h.style.width=e.expandedWidth+"px";h.style.height=e.expandedHeight+"px"}if(d)h.style.display="block";c.appendChild(h);if(a.shouldDisplayHTML5Asset){h.onmouseover=new Function("dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onMouseOverHtml5('"+e.variableName+"');");h.onmouseout=new Function("dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onMouseOutHtml5('"+e.variableName+"');");h.ontouchstart=new Function("dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onTouchHtml5('"+
e.variableName+"');");h.ontouchend=new Function("dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onTouchEndHtml5('"+e.variableName+"');");var i=this.displayManager.createHTML5AdIframe(e);h.appendChild(i);this.displayManager.html5IframeId=i.id}else{var j="dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onMouseOut('"+e.variableName+"');";var k="dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onMouseOver('"+e.variableName+"');";var l=e.url;var m=e.queryString+"&td="+escape(self.location.hostname)+
"&wmode="+e.wmode;m+=b.usesSalignForExpanding(e.salign,e.wmode)?"&scaleMode=noScale":"";m+="&ispushdown="+e.pushContents;RichMediaCore_60_10.prototype.trackCsiEvent("fb");h.innerHTML=this.flashUtil.getObjectHtml("id","FLASH_"+e.variableName,"name","FLASH_"+e.variableName,"WIDTH",e.expandedWidth,"HEIGHT",e.expandedHeight,"movie",l,"quality","high","wmode",e.wmode,"salign",e.salign,"queryString",m,"onmouseover",k,"onmouseout",j)}};
ExpandingIFrameRenderer_60_10.prototype.createOuterDiv=function(a){var b=document.createElement("DIV");b.id="OUTER_DIV_"+a.variableName;b.style.position="relative";b.style.zIndex=a.zIndex;if(a.expandingDivStyleSheet!="")this.applyCSSProperties(b,a.expandingDivStyleSheet);return b};
ExpandingIFrameRenderer_60_10.prototype.createTable=function(a,b){var c=document.createElement("TABLE");c.style.width=a.width+"px";c.style.height=a.height+"px";var d=a.pushContents&&this.isInternetExplorer()&&this.getIEVersion()>=8;if(a.displayInline&&!d)c.style.display=this.isSafari()||this.isChrome()?"inline-table":"inline";if(a.cssProperty!="")if(a.displayInline&&a.expandingDivStyleSheet!="")this.applyCSSProperties(c,a.expandingDivStyleSheet);else this.applyCSSProperties(c,a.cssProperty);for(var e in a.styleProperties)c.style[e]=
a.styleProperties[e];c.cellPadding=0;c.cellSpacing=0;c.border=0;var f=document.createElement("TBODY");var g=document.createElement("TR");var h=document.createElement("TD");g.style.padding="0px";g.style.margin="0px";g.style.borderStyle="none";g.style.borderWidth="0px";h.style.padding="0px";h.style.margin="0px";h.style.borderStyle="none";h.style.borderWidth="0px";h.appendChild(b);g.appendChild(h);f.appendChild(g);c.appendChild(f);return c};
ExpandingIFrameRenderer_60_10.prototype.createPlaceholderElement=function(a){var b=document.createElement("IMG");b.id="EXPANDO_PLACEHOLDER_"+a.variableName;b.src=creative.mediaServer+"/dot.gif";b.width=parseInt(a.width);b.height=parseInt(a.height);b.style.width=a.width+"px";b.style.height=a.height+"px";b.style.visibility="hidden";return b};ExpandingIFrameRenderer_60_10.prototype.minimizeAdIframe=function(a){if(a.width!="")a.width=0;if(a.height!="")a.height=0;a.style.width="0px";a.style.height="0px"};
ExpandingIFrameRenderer_60_10.prototype.processExpandingBreakout=function(a,b,c,d){try{var e=a.assets[this.ASSET_TYPE_EXPANDING];var f=this.createOuterDiv(e);var g=b.parentNode;if(c){f.style.display="block";this.adjustParentOverflowStyle(g)}var h=this.createTable(e,f);g.insertBefore(h,b);if(a.adjustOverflow)d.adjustParentOverflow(f);var i=this.createPlaceholderElement(e);this.minimizeAdIframe(b);f.appendChild(i);this.createExpandingDiv(a,d,f,c);this.displayManager.registerCreativeElement(h);this.displayCreative(a)}catch(j){}};
ExpandingIFrameRenderer_60_10.prototype.adjustParentOverflowStyle=function(a){for(var b=a;b;){if(b.tagName!="BODY"||this.isFirefox()){var c=this.getStyle(b);if(c.overflow=="hidden"||c.overflowX&&(c.overflowX=="hidden"||c.overflowX=="auto")||c.overflowY&&(c.overflowY=="hidden"||c.overflowY=="auto"))b.style.overflow="visible"}if(b.tagName=="BODY")break;b=b.parentNode}};
ExpandingIFrameRenderer_60_10.prototype.applyCSSProperties=function(a,b){var c=b.split(";");for(var d=0;d<c.length;d++)if(c[d].indexOf(":")!=-1){var e=c[d].split(":");a.style[e[0]]=e[1]}};
ExpandingIFrameRenderer_60_10.prototype.displayCreative=function(a){var b=a.assets[this.ASSET_TYPE_EXPANDING];if(a.shouldDisplayHTML5Asset)this.displayManager.attachMessageHandler();else{this.displayManager.doNotAdjustObject(b.variableName,"FLASH_"+b.variableName);this.displayManager.fsHook("FLASH_"+b.variableName)}this.displayManager.registerUrl(a.renderingId,a.adserverUrl);this.displayManager.addEntityProperties(b.variableName,b.hideDropdowns,b.hideIframes,b.hideScrollbars,b.hideObjects,b.hideApplets,
true);this.displayManager.scheduleDisplay(b.variableName,b.duration,false);if(a.shouldDisplayHTML5Asset)this.displayManager.logHTML5Impression();this.displayManager.collapseAsset(b.variableName);if(!a.shouldDisplayHTML5Asset&&this.displayManager.isFlashScriptingSupported()){this.displayManager.scheduleCallbackOnLoad("triggerPoliteDownload()");this.displayManager.triggerDispatchScriptLoaded()}};function IFrameCreativeRenderer_60_10(){}IFrameCreativeRenderer_60_10.prototype=new RichMediaCore_60_10;
IFrameCreativeRenderer_60_10.prototype.removeCreative=function(a,b){var c=dartCreativeDisplayManagers[a];if(typeof c=="undefined"||c==null)return;if(c.creative.type==this.CREATIVE_TYPE_EXPANDING&&!b)this.revertExpandingAdChanges(a,c);c.removeArrayElement(dartCallbackObjects,c);c.deleteCreative(b);dartCreativeDisplayManagers[a]=null};
IFrameCreativeRenderer_60_10.prototype.revertExpandingAdChanges=function(a,b){var c=self.document.getElementsByTagName("iframe");for(var d=0;d<c.length;d++)if(typeof c[d].MotifIFrameIDArray!="undefined")for(var e=0;e<c[d].MotifIFrameIDArray.length;e++)if(c[d].MotifIFrameIDArray[e]==a){var f=b.creative.assets[this.ASSET_TYPE_EXPANDING];c[d].width=f.width;c[d].height=f.height;c[d].style.width=f.width+"px";c[d].style.height=f.height+"px";break}};
IFrameCreativeRenderer_60_10.prototype.displayCreative=function(a,b){var c=false;if(typeof a.MsnDapIF!="undefined"&&a.MsnDapIF)c=true;var d=new RichMediaCreativeDisplayManager_60_10(a,b);if(a.type==this.CREATIVE_TYPE_FLOATING){dartCreativeDisplayManagers[a.creativeIdentifier]=d;var e=new FloatingManager_60_10(a,d);var f=a.assets[this.ASSET_TYPE_FLOATING];if(this._isValidStartTime(f.startTime))d.registerTimeoutHandler(eval(f.startTime)*1000,"displayFloatingFlash()",e)}else if(a.type==this.CREATIVE_TYPE_EXPANDING){dartCreativeDisplayManagers[a.creativeIdentifier]=
d;var g=new ExpandingManager_60_10(a,d);d.setExpandingManager(g);var h=new ExpandingIFrameRenderer_60_10(d,g,a);h.processExpandingBreakout(a,b,c,g)}else if(a.type==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING){dartCreativeDisplayManagers[a.creativeIdentifier]=d;var i=new InpageIFrameRenderer_60_10(a,d);f=a.assets[this.ASSET_TYPE_FLOATING];e=new FloatingManager_60_10(a,d);d.setFloatingManager(e);i.processInpageBreakout(a,b,c,e);if(this._isValidStartTime(f.startTime))d.registerTimeoutHandler(eval(f.startTime)*
1000,"displayFloatingFlash()",e)}};IFrameCreativeRenderer_60_10.prototype.processCreative=function(a){var b=self.richMediaIFrameCreatives[a].creative;var c=self.richMediaIFrameCreatives[a].sourceIFrameArray.shift();this.displayCreative(b,c)};IFrameCreativeRenderer_60_10.prototype.showCreative=function(a){if(this.isFirefox()||this.isSafari()||this.isChrome())this.processCreative(a);else this.registerPageLoadHandler("processCreative('"+a+"')",this)};
IFrameCreativeRenderer_60_10.prototype.loadPlCrJs=function(a,b,c){var d=c.document.createElement("SCRIPT");RichMediaCore_60_10.prototype.trackCsiEvent("pb");d.src=a;var e=c.document.getElementsByTagName("head");if(this.isInternetExplorer()&&e.length>0)e[0].appendChild(d);else if(b.parentNode.parentNode)b.parentNode.parentNode.appendChild(d);else b.parentNode.insertBefore(d,b)};
IFrameCreativeRenderer_60_10.prototype.isGlobalTemplateCompatible=function(a){var b="expandingIframe";if(a.globalTemplateVersion!="60_10")return false;switch(a.type){case this.CREATIVE_TYPE_FLOATING:return b=="floatingIframe";case this.CREATIVE_TYPE_EXPANDING:return b=="expandingIframe";case this.CREATIVE_TYPE_INPAGE_WITH_FLOATING:return b=="inpageFloatingIframe";default:return false}};
IFrameCreativeRenderer_60_10.prototype.loadPlcrScripts=function(){for(var a in self.richMediaIFrameCreatives){var b=self.richMediaIFrameCreatives[a];var c=b.baseCreative;RichMediaCore_60_10.prototype.setCsiEventsRecordedDuringBreakout(c);if(this.isGlobalTemplateCompatible(c))for(var d=0;d<b.sourceIFrameArray.length;d++){var e=b.sourceIFrameArray[d];var f=b.plcrScript;this.loadPlCrJs(f,e,self)}}};(new IFrameCreativeRenderer_60_10).loadPlcrScripts();RichMediaCore_60_10.prototype.trackCsiEvent("ge");